### ISSUE TITLE
TEMPLATE

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/einander-helfen#1]
**Reason**
Why do you want this feature? What goals should be achieved? Is your issue related to a problem? Please describe.

**Solution**
Describe the solution you'd like

**Alternatives**
Describe alternatives you've considered

**Effects**
What effects does your proposed solution have?

**Acceptance criteria**
Describe acceptance criteria for testing

**Additional context**

**Comment by jschurse** [comment]
The templates for feature requests and bug reports have been added.
