### ISSUE TITLE
Usability review and improvements

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#122]
**Reason (Why?)**
The design of the result page shall be as good as possible for all kinds of users.

**Solution (What?)**
A usability review should be conducted and the design of the site should be improved.

Things that could possibly be changed:
- Add a small button in the lower right corner which allows you to go back to the top of the page. See #355
- If you switch the post page, the scrolling should be reseted. See #329 
- If you switch the post, the scrolling inside the details view should be reseted. #236 
- Tags should be aggregated if they are too long/too many and increase the searchbar height
- Accessability:
  - color contrasts to support color blind persons
  - alt-lables for buttons, pictures etc.
- Improve performance (see results of Lighthouse-Test)

**Not doing**
This issue is only for the design.

**Relation to other Issues**
None

**Acceptance criteria**

**Comment by BaderChouaib** [comment]
Notes from the usability review conducted by Marcel Obel on 02.07.2020 (in german)
![grafik](https://user-images.githubusercontent.com/25898717/86514079-b0e7f580-be0f-11ea-8b00-daac8d6fb5f3.png)

**Comment by sgrobarek** [comment]
I created a new toolbar header on the home page related to the size of the search bar. See attached screenshots with descending resolution: 4k, 1080p, 720p, ipad, iphone. I also changed the size from the header on the home page to the header size on the result page.
![Screen Shot 2020-07-07 at 06 53 42](https://user-images.githubusercontent.com/64202529/86770900-6f2d9980-c01f-11ea-8d11-c30f565b8332.png)
![Screen Shot 2020-07-07 at 06 53 29](https://user-images.githubusercontent.com/64202529/86770973-840a2d00-c01f-11ea-8e13-bd606def6f56.png)
![Screen Shot 2020-07-07 at 06 53 24](https://user-images.githubusercontent.com/64202529/86770978-853b5a00-c01f-11ea-9f4d-f65fd59d90cb.png)
![Screen Shot 2020-07-07 at 06 54 28](https://user-images.githubusercontent.com/64202529/86770984-87051d80-c01f-11ea-8500-29f4c5445260.png)
![Screen Shot 2020-07-07 at 06 54 33](https://user-images.githubusercontent.com/64202529/86770989-879db400-c01f-11ea-818f-e4f3cc958786.png)
