### ISSUE TITLE
Rename resultPage to posts

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#125]
**Reason (Why?)**
The name of the vue file should match to the URI.

**Solution (What?)**
Rename the file resultPage.vue to posts.vue.

Attention:
This should only be done when no work is being done on the side, as this can lead to major conflicts.

**Not doing**
None

**Relation to other Issues**
None

**Acceptance criteria**
The file posts.vue exists.

**Comment by xcaverxiii** [comment]
This is done by #333.

**Comment by DianaPankratz** [comment]
See #333
