### ISSUE TITLE
Location suggestion does not work properly on Android with Firefox

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#128]
**Describe the bug**
Location suggestion does not work properly on mobile.

**To Reproduce**

1. Go to 'home' via smartphone
2. Click on 'the location textfield'
3. Type a zipcode like ‘63110’ or a location like ‘Frankfurt’

**Expected behavior**
Matching locations should be suggested for the incompleted as well as for the completed input.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64203299/86294329-9c7be100-bbf4-11ea-9adb-28fb654c7500.png)

**Desktop (please complete the following information):**
/

**Smartphone (please complete the following information):**

    Device: OnePkus 6T
    OS: Android 10
    Browser Firefox
    Version 86.9.0

**Additional context**
This bug was already fixed in #51, but it still does not work in Firefox.

**Comment by FiedlerJan** [comment]
I can't reproduce this bug anymore. Can someone verify that this bug still exists.

**Comment by jonas-hda** [comment]
I couldn't reproduce this bug using a smartphone or the mobile view on desktop.

The bug no longer seems to exist and the issue can be closed.
