### ISSUE TITLE
Implementation of location based search

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/einander-helfen#13]
In the [current draft for the front-end](https://cai-einander-helfen.fbi.h-da.de/) there is a possibility to enter a location for a location and range based search.
To better understand the requirements for this feature I request clarification of the following questions:

What and how many locations should be listed?

Where do we get these locations from?

To use this data in ElasticSearch we need to resolve the names to lon/lat values. Which service are we going to use for that?

**Comment by BernhardHumm** [comment]
To implement location based search there are two ends to be considered: 

(a) location search input by user 

(b) location information in data

 

 

Ad (a) location search input by user:

 

There are two input fields for location information: 

1.       location (text input field with autosuggest) 

2.       range (dropdown: e.g., 10km, 25km, 50km, everywhere)

 

In the location text input field, the user shall be able to enter all cities or PLZ (ZIP codes) in Germany . The AutoSuggest shall allow selecting one. 

Data basis, e.g. https://www.suche-postleitzahl.org/downloads

Suggestion: load the city names and PLZ on the start of the web app (size shouldn’t be too large) and use in autoSuggest.

 

The data for AutoSuggest must contain the following attributes:

*       name, e.g., „Friedberg(Hessen)“

*       ZIP code: e.g., 61169

*       lat, lon

*       rank

 

Name and ZIP are used for autoSuggest and are displayed. E.g. 

*       entering “Fried” -> autoSuggest “61169 Friedberg (Hessen)

*       entering “611” -> autoSuggest “61169 Friedberg (Hessen)

 

lat, lon are used for querying the ElasticSearch server.

rank reveals the size of city (area) and is used for selecting autosuggest entries if there are too many matches (see below).

 

Special case: Cities with several ZIP codes, e.g., Frankfurt. 

Then, an additional entry for all ZIP codes shall be suggested, 

e.g., entering “Frankf” -> autsuggest:

*       Frankfurt am Main (alle)

*       Frankfurt (Oder) (alle)

*       60306 Frankfurt am Main

*       60314 Frankfurt am Main

*       15230 Frankfurt (Oder)

*       15232 Frankfurt (Oder)

 

The lat, lon for for an aggregated entry like “Frankfurt am Main (alle)” shall be in the center of the city.

 

AutoSuggest shall be limited to 10 entries. If there are more candidates matching the search string, a selection shall be made based on relevance (rank of entry reveals size of city) and diversity (e.g., regional difference).  A good example is Frankfurt above: various examples of Frankfurt am Main and Frankfurt (Oder) are displayed. 

 

Browser location information: 

If the browser of the used contains location information, then location text field shall be initialized with this location (range initialized with “everywhere)

 

 

 

Ad (b) location information in data

 

Each post in the data base shall contain lat, lon. Finding a suitable lat, lon for each post is part of the semantic enrichment process in ETL.

During search, the Geo-distance query feature of ElasticSearch can be used:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html 

Here, the lat/lon information from the autoSuggest of the location search input and the range information by the user are used as query inputs and the lat/lon information of the data is matched. 

 

 

------------------------------------

 

 

Von: jschurse [mailto:notifications@github.com] 
Gesendet: Samstag, 23. Mai 2020 21:28
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Assign <assign@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Implementation of location based search (#13)

 

Assigned #13 <https://github.com/hochschule-darmstadt/einander-helfen/issues/13>  to @BernhardHumm <https://github.com/BernhardHumm> .
