### ISSUE TITLE
A single search results opens the detail view directly

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#130]
**Describe the bug**
If the search has only one result, the detail view is opened directly and not the map

**To Reproduce**
1. Go to 'https://cai-einander-helfen-staging.fbi.h-da.de/posts/8bba27c43f202713c745f2d1704a1725?q=Jugendarbeit&location=60306%20Frankfurt%20am%20Main%20%28alle%29&radius=25km&page=1'
2. The detail view is shown

**Expected behavior**
If the user gets only one result, the map should be displayed with only one pin.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 78

**Smartphone (please complete the following information):**
Not used.

**Additional context**
None

**Comment by jschurse** [comment]
This is not a bug, but a requirement:
https://github.com/hochschule-darmstadt/einander-helfen/issues/30#issuecomment-642523234

**Comment by BernhardHumm** [comment]
Yes, I think this is a good feature (convenience for user)

 

 

 

------------------------------------

 

 

Von: Jenja Schurse [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2020 12:14
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] A single search results opens the detail view directly (#130)

 

This is not a bug, but a requirement:
#30 (comment) <https://github.com/hochschule-darmstadt/einander-helfen/issues/30#issuecomment-642523234>
