### ISSUE TITLE
Homepage: Searching with 'Enter' 

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#131]
**Reason (Why?)**
In addition to the search button the user should be able to search with 'Enter'.

**Solution (What?)**
After the user types something in the searchbar and an autosuggest exists, he or she can select the suggested value with the first 'Enter'. If he or she presses 'Enter' again the search should start and lead to the resultpage.

**Not doing**
The search algorithm is already implemented.

**Relation to other Issues**
#42 

**Acceptance criteria**
If an autosuggest exists for the search, the user should be able to select it with the first 'Enter'. After he/she presses 'Enter' again the search should start and lead to the resultpage. If there is no autosuggest for the search value the first 'Enter' starts the search.

**Comment by BernhardHumm** [comment]
The same should happen when the user selects a location and then presses <Enter>

 

P.S. avoid redundance in the issue description (DRY principle). Leave section “acceptance criteria” empty if there is nothing more than what has already been described. 

 

 

 

------------------------------------

 

 

Von: MaiThiD [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2020 12:16
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Homepage: Searching with 'Enter' (#131)

 

Reason (Why?)
In addition to the search button the user should be able to search with 'Enter'.

Solution (What?)
After the user types something in the searchbar and an autosuggest exists, he or she can select the suggested value with the first 'Enter'. If he or she presses 'Enter' again the search should start and lead to the resultpage.

Not doing
The search algorithm is already implemented.

Relation to other Issues
#42 <https://github.com/hochschule-darmstadt/einander-helfen/issues/42> 

Acceptance criteria
If an autosuggest exists for the search, the user should be able to select it with the first 'Enter'. After he/she presses 'Enter' again the search should start and lead to the resultpage. If there is no autosuggest for the search value the first 'Enter' starts the search.
