### ISSUE TITLE
Open all hyperlinks in a new tab

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#132]
**Reason (Why?)**
If the user clicks on a link, the source shall be opened in a new tab.

**Solution (What?)**
All links in the detail view should be opened in a separate tab.

**Not doing**
This issue focuses on the detailed view.

**Relation to other Issues**
None

**Acceptance criteria**
A link on the detail view opens a new tab.

**Comment by BaderChouaib** [comment]
See discussion in #144.
Please use the "frontend" and "backend" labels to prevent confusion for future issues

**Comment by BaderChouaib** [comment]
Done by @marvinseith
Still missing rel="noopener noreferrer" so ill leave this open for now

**Comment by marvinseith** [comment]
Fixed, will be added with next PR. Closed.
