### ISSUE TITLE
Display the distance to an post

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#133]
**Reason (Why?)**
The user shall be able to see how far a post is from his search location.

**Solution (What?)**
Every post should display a distance from the search location to the post location. It should be displayed in the result view.

**Not doing**
None

**Relation to other Issues**
#43: Implements the distance based search.

**Acceptance criteria**
Each post shows the distance.

**Comment by jschurse** [comment]
![grafik](https://user-images.githubusercontent.com/12964877/86349058-d8e52680-bc60-11ea-8f0d-71625bd3e290.png)

What do you think of this?

**Comment by andresesam** [comment]
I'd maybe highlight the radius. I had to look a bit closer (and with the background info that the radius is shown) to discover it at all :D

**Comment by BernhardHumm** [comment]
Of course only for location search.

 

Display distance in km.

 

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2020 12:37
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Display the distance to an post (#133)

 

Reason (Why?)
The user shall be able to see how far a post is from his search location.

Solution (What?)
Every post should display a distance from the search location to the post location. It should be displayed in the result view.

Not doing
None

Relation to other Issues
#43 <https://github.com/hochschule-darmstadt/einander-helfen/issues/43> : Implements the distance based search.

Acceptance criteria
Each post shows the distance.

**Comment by jschurse** [comment]
Fixed by #134
