### ISSUE TITLE
About page should be grammatically correct and a new paragraph should be added 

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#136]
**Reason (Why?)**
The content of the about page should be grammatically correct.

**Solution (What?)**
Change the following part in the first row of "einander-helfen.org":  
"...und ehrenamtliche Tätigkeiten: mit eine..."  to 
"...und ehrenamtliche Tätigkeiten: **Mit** eine..."

Change the following part in "Wer wir sind":
"Wer wir sind: Wir sind **selbst** ein ehrenamtliches Team … " to
"Wer wir sind: Wir sind ein ehrenamtliches Team …" 

Adding new paragraph (in "Wer wir sind") with the following text:
**THIS WILL BE ADDED LATER**

**Not doing**
Implementing "Über uns".

**Relation to other Issues**
#46 

**Acceptance criteria**
The text has been corrected.

**Comment by BernhardHumm** [comment]
New Paragraph in section „Und so funktioniert’s“:

 

einander-helfen.org fasst Angebote von mehreren Anbietern im deutschsprachigen Raum zusammen und erlaubt es, bequem über alle zu suchen. Aktuell werden folgende Anbieter abgedeckt:

 

*       www.ehrenamtssuche-hessen.de <http://www.ehrenamtssuche-hessen.de>  [href: https://www.ehrenamtssuche-hessen.de ]

 

Weitere Anbieter folgen.

Fehlt Ihnen etwas? Dann kontaktieren Sie uns gerne unter info@einander-helfen.org <mailto:info@einander-helfen.org>  .

 

 

 

 

------------------------------------

 

 

Von: MaiThiD [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2020 12:55
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] About page should be grammatically correct and a new paragraph should be added (#136)

 

Reason (Why?)
The content of the about page should be grammatically correct.

Solution (What?)
Change the following part in the first row of "einander-helfen.org":
"...und ehrenamtliche Tätigkeiten: mit eine..." to
"...und ehrenamtliche Tätigkeiten: Mit eine..."

Change the following part in "Wer wir sind":
"Wer wir sind: Wir sind selbst ein ehrenamtliches Team … " to
"Wer wir sind: Wir sind ein ehrenamtliches Team …"

Adding new paragraph (in "Wer wir sind") with the following text:
THIS WILL BE ADDED LATER

Not doing
Implementing "Über uns".

Relation to other Issues
#46 <https://github.com/hochschule-darmstadt/einander-helfen/issues/46> 

Acceptance criteria
The text has been corrected.

**Comment by BaderChouaib** [comment]
The href to ehrenamtsuche-hesse.de should open in a new tab (set attributes target="_blank" and rel="noopener noreferrer")

**Comment by andresesam** [comment]
> The href to ehrenamtssuche-hessen.de should open in a new tab (set attributes target="_blank" and rel="noopener noreferrer")

Feel free to change it. 😄

**Comment by jschurse** [comment]
> 
> 
> > The href to ehrenamtssuche-hessen.de should open in a new tab (set attributes target="_blank" and rel="noopener noreferrer")
> 
> Feel free to change it. 😄

I felt free.
