### ISSUE TITLE
Hide the copyright tag

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#137]
**Reason (Why?)**
The data from Ehrenamtssuche Hessen shall be taken over as exactly as possible. The copyright tag shall be hidden so that it is not shown in the detail view.

**Solution (What?)**
The span, which contains the tag strong with the class 'shameOnYouIfRemove', should be hidden with css.
![grafik](https://user-images.githubusercontent.com/64203299/86350477-09c65b00-bc63-11ea-9694-1556ea0287ce.png)

**Not doing**
None

**Relation to other Issues**
None

**Acceptance criteria**
Ehrenamtssuche Hessen -' is not shown in the detail view, but is available in html.

**Comment by BaderChouaib** [comment]
We need to wait for this until the html tags are back on text heavy properties. Currently they are filtered out on the backend:
![grafik](https://user-images.githubusercontent.com/25898717/86482037-6ef87a00-bd51-11ea-82cc-fbb5f772a96c.png)

**Comment by jschurse** [comment]
@marvinseith @JamieArmstrongArndt is there en ETA for this update in the crawler?

**Comment by marvinseith** [comment]
Probably tomorrow

**Comment by marvinseith** [comment]
Doing this right now, the 'shameOnYouIfRemove' class will then also be present in the organization text. It needs to be filtered out there too.
