### ISSUE TITLE
Location searchbar: Selecting an item from autosuggest does not work for all items

### ISSUE THREAD

**Issue by BaderChouaib** [hochschule-darmstadt/einander-helfen#141]
**Describe the bug**
When selecting an item from autosuggestion in the location searchbar autocompletion does not work on some items. Instead the location searchbar is just empty. When retrying with the same item, autocompletion works correctly, however when routing to resultPage the location field is empty (not its only visually working on second try). The bug appears on location searchbar inside the header and on the home page

**To Reproduce**
1. Enter Home.vue
2. Type "I" into the location searchbar (you can autocomplete more characters towards "Idenheim")
3. Pick "54636 Idenheim" (press enter or pick via mouse)
The location searchbar should be empty now, which is incorrect
Retrying will result in the correct behaviour (dont reload the page)

**Expected behavior**
All selected items from location autocompletion should update the location searchbar with the items content

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version 83, 77

**Additional context**
This works on a lot of different terms. For example "54518 Hupperath", "17291 Uckerfelde" and "18276 Plaaz".
Causing the bug on one of these does not count as "first time" when trying with other buggy autosuggested items. When typing in the zipcode / PLZ of those buggy items, autosuggestion does not show the buggy item as an option. So the cause of the bug is most likely a mismatch between zipcode and location.

**Comment by xcaverxiii** [comment]
@DianaPankratz  @KaiDrieHda please check if this is still an issue on staging.

**Comment by DianaPankratz** [comment]
@xcaverxiii seems to be fixed. I will close this issue.
