### ISSUE TITLE
ResultPage: Route user to offer url when clicking on the provider icon?

### ISSUE THREAD

**Issue by BaderChouaib** [hochschule-darmstadt/einander-helfen#142]
**Reason (Why?)**
This would reduce effort from the users perspective by not scrolling down to the "Zum Angebot" button.
Could also be implemented from list view of posts (left hand side). That way the user does not even have to select the post, but could route directly to the offer instead.

**Solution (What?)**
Put an href with the url to the offer behind the provider icon. On detailed and list view.
Routing should be done in a new tab

**Comment by MaiThiD** [comment]
This issue is unneccessary because the logos will be completely removed.
