### ISSUE TITLE
Posts from Ehrenamtssuche-Hessen sometimes missing

### ISSUE THREAD

**Issue by JamieArmstrongArndt** [hochschule-darmstadt/einander-helfen#156]
**Describe the bug**
After the ETL process for [Ehrenamt-Hessen](https://www.ehrenamtssuche-hessen.de) is finished the Elastic Index 'posts' is missing entries (compared to the count displayed on the website). The error log indicates, that the scraping of the URLs from a searchpage i.e. [the second page](https://www.ehrenamtssuche-hessen.de/entry_search_result.cfm?searchterm=&sectorIds=&zip=&page=2&countyId=0&locationId=0&distance=0&entryTypeId=0) (where 15 entries are displayed per page) has some 'hick-ups', so instead of scraping new URLs from the following page the scraped URLs are duplicates to previous scraped detail page URLs. 

**To Reproduce**
Start the ETL-Process for all pages and in most cases the error will occur. This bug is hard to reproduce, because it seems like corresponding server may be timing out, blocking incoming requests or is just simply very slow. 

**Expected behavior**
The count of all ehrenamt-hessen jobs on [the search page](https://www.ehrenamtssuche-hessen.de/?formAutosubmit=true&showEntryTypeFilterSelect=true&searchTab=entries&searchterm=&locationCounty=0&countyId=0&locationId=0&selectedSectorPanel=&entryTypeId=5) is different to the post count returned by the scraping process (currently on 14.07.2020 having **1.888 entries**, the extraction process returns around 1700 to 1850 posts). 

**Additional context**
The described bug varies with each running process and is hard to pinpoint. The issue is most likely related to problems with the backend of the scraped domain.

**Comment by FiedlerJan** [comment]
This issue is done by reworking the Ehrenamtssuche-Hessen scraper.
