### ISSUE TITLE
Install analytics tools to track site usage

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/einander-helfen#164]
**Reason (Why?)**
To be able to best serve the needs of our users we need more information about them.
An analytics tool like [Matomo](https://matomo.org/) can collect information about our users (e.g what devices they are using, browser versions, display resolutions, etc.) and give use hints where we need to focus our enhancements of the application.

**Solution (What?)**
Setup an Matomo instance and integrate a plugin like https://github.com/AmazingDreams/vue-matomo to enable the analytics feature for our app.

**Not doing**
We do not want to collect sensitive user data and we definitely don't want this information to fall into the wrong hands. So a self hosted solution is required. 

**Acceptance criteria**
Page calls are logged with information about the device doing these calls. The collected information is anonymized.

**Comment by KaiDrieHda** [comment]
Duplicate issue. See #339
