### ISSUE TITLE
Crawlers for various websites

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/einander-helfen#165]
**Reason (Why?)**
The usefulness of einander-helfen.org depends on the number of posts being offered by many organizations

**Solution (What?)**
1. Perform a survey of websites to crawl. Categorize according to usefulness and ease of crawler implementation
2. Prioritize crawler implementations; distribute in teams
3. Implement crawler analogously to ehrenamtssuche-hessen.de , test, integrate with other crawlers and deploy in live system

Examples of websites are:

- https://www.aktion-mensch.de/projekte-engagieren-und-foerdern/freiwilliges-engagement/aktiv-werden.html
- http://www.diakonie-wuerttemberg.de/jobs-und-mitwirken/ehrenamt/freiwilligensuche-ehrenamtliche-taetigkeiten/
- http://www.ehrenamtsportal.de/
- https://www.caritas.de/spendeundengagement/engagieren/ehrenamt/ehrenamtsangebote/ehrenamtsboerse/ehrenamts-angebote.aspx
- http://www.ran-ans-leben-diakonie.de/freiwilligenprojekte/angebot-finden/angebote-ehrenamt-freiwillige-mitarbeit-suchen
- https://www.berlin.de/buergeraktiv/engagieren/buerger/ehrenamtssuche/index.cfm?dateiname=ehrenamt_suche.cfm&anwender_id=5
- http://www.bagfa.de/freiwilligenagenturen.html
- http://www.ehrenamt.de/1419_Ehrenamt_finden.htm
- http://www.ehrfinder.de/jobsuche/
- https://www.buergerstiftungen.org/
- https://www.aktive-buergerschaft.de/buergerstiftungen/modell-buergerstiftung/

**Out of scope**

**Relation to other Issues**

**Acceptance criteria**

**Comment by FiedlerJan** [comment]
To solve this issue, a sheet was created. The sheet can be found under the following link.
https://lernen.h-da.de/mod/url/view.php?id=443150

If you have other pages that should be viewed and possibly considered, please add them to the list.
