### ISSUE TITLE
Automated crawling for live server

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/einander-helfen#166]
**Reason (Why?)**
The usefulness of einander-helfen.org depends on the posts being up-to-date. Currently, automated crawling is performed on the staging server only; pushing index to the live server is a manual act.

**Solution (What?)**
Automatically update the index on the live server regularly.

To be decided: perform crawling on the live server vs. move crawling results from staging server to live server.

**Out of scope**

**Relation to other Issues**

**Acceptance criteria**

**Comment by FiedlerJan** [comment]
Also, the cronjob on the staging is to be removed.

**Comment by FiedlerJan** [comment]
Cronjob is added from the live and removed for the staging server. Updated the [wiki](https://github.com/hochschule-darmstadt/einander-helfen/wiki/System-Architecture#execution).
