### ISSUE TITLE
ETL process pipeline diagram

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#168]
**Reason (Why?)**
Currently, there is only a written explanation of the ETL process. This can be found in the Wiki. However, it is always helpful if the process is also graphically displayed. This gives you a better overview more quickly.

**Solution (What?)**
Create a sequence diagram which covers the hole ETL process.

**Out of scope**
None

**Relation to other Issues**
None

**Acceptance criteria**
A sequence diagram was created, which represents the entire ETL process and can be easily understood.

**Comment by BernhardHumm** [comment]
I suggest a BPMN Diagram (not UML sequence diagram).

Suggested tool: https://www.yworks.com/products/yed 

 

 

 

 

Von: JanF <notifications@github.com> 
Gesendet: Samstag, 14. November 2020 19:12
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] ETL process pipeline diagram (#168)

 

Reason (Why?)
Currently, there is only a written explanation of the ETL process. This can be found in the Wiki. However, it is always helpful if the process is also graphically displayed. This gives you a better overview more quickly.

Solution (What?)
Create a sequence diagram which covers the hole ETL process.

Out of scope
None

Relation to other Issues
None

Acceptance criteria
A sequence diagram was created, which represents the entire ETL process and can be easily understood.

**Comment by FiedlerJan** [comment]
Below the created BPMN diagramm. The working files can be found in NextCloud. In NextCloud are also more detailed sequence diagrams.
http://141.100.60.99:81/index.php/apps/files/?dir=/EinanderHelfen/Software%20architecture/Etl&fileid=5271

![einanderhelfen_etl_bpmn](https://user-images.githubusercontent.com/64203299/99417767-93b54e80-28fa-11eb-935e-1ac5ccb0a0e2.png)

**Comment by BernhardHumm** [comment]
This is a nice conceptual overview.

It would be also good to have an overview of the implemented process: Which files (one file per crawled website / many files? .csv / .json?), what are the names of the Python modules to be called? etc. Similar to the diagram for the openArtBrowser ETL process.

 

 

 

 

Von: JanF <notifications@github.com> 
Gesendet: Dienstag, 17. November 2020 17:33
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] ETL process pipeline diagram (#168)

 

Below the created BPMN diagramm. The working files can be found in NextCloud. In NextCloud are also more detailed sequence diagrams.
http://141.100.60.99:81/index.php/apps/files/?dir=/EinanderHelfen/Software%20architecture/Etl <http://141.100.60.99:81/index.php/apps/files/?dir=/EinanderHelfen/Software%20architecture/Etl&fileid=5271> &fileid=5271

 <https://user-images.githubusercontent.com/64203299/99417767-93b54e80-28fa-11eb-935e-1ac5ccb0a0e2.png>

**Comment by FiedlerJan** [comment]
I updated the diagram. Please let me know if it meets the expections.

![einanderhelfen_etl_bpmn](https://user-images.githubusercontent.com/64203299/99565240-b2374a80-29cb-11eb-955f-d14f05f72164.png)

I also updated the files in NextCloud.

**Comment by BernhardHumm** [comment]
Yes, thank you!

 

 

 

 

Von: JanF <notifications@github.com> 
Gesendet: Mittwoch, 18. November 2020 18:29
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] ETL process pipeline diagram (#168)

 

I updated the diagram. Please let me know if it meets the expections.

 <https://user-images.githubusercontent.com/64203299/99565240-b2374a80-29cb-11eb-955f-d14f05f72164.png> 

I also updated the files in NextCloud.
