### ISSUE TITLE
Create privacy page filled with content generated from e-recht24.de/impressum-generator.html

### ISSUE THREAD

**Issue by BaderChouaib** [hochschule-darmstadt/einander-helfen#17]
**Reason (Why?)**
A privacy page is a necessary requirement when going online with einander-helfen.de

**Solution (What?)**
Generate content for the page with e-recht24.de/impressum-generator.html. As a responsible person please use Roland Humm's contact adress, which was sent by Pr. Dr. Humm via eMail

**Not doing**
Dont contact site providers asking them for permission to crawl their advertisements

**Relation to other Issues**
#16 

**Acceptance criteria**
Privacy page gets a pass on review with Roland Humm

**Comment by BernhardHumm** [comment]
Use the following email address for Roland Humm:

info@einander-helfen.org

 

 

------------------------------------

 

Von: BaderChouaib [mailto:notifications@github.com] 
Gesendet: Montag, 25. Mai 2020 22:54
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Create privacy page filled with content generated from e-recht24.de/impressum-generator.html (#17)

 

Reason (Why?)
A privacy page is a necessary requirement when going online with einander-helfen.de

Solution (What?)
Generate content for the page with e-recht24.de/impressum-generator.html. As a responsible person please use Roland Humm's contact adress, which was sent by Pr. Dr. Humm via eMail

Not doing
Dont contact site providers asking them for permission to crawl their advertisements

Relation to other Issues
#16 <https://github.com/hochschule-darmstadt/einander-helfen/issues/16> 

Acceptance criteria
Privacy page gets a pass on review with Roland Humm
