### ISSUE TITLE
Optimize the result page header

### ISSUE THREAD

**Issue by LeDrieHda** [hochschule-darmstadt/einander-helfen#173]
**Reason (Why?)**
We need to improve the usability on einander-helfen.org.

**Solution (What?)**
Implement a user friendly and layout-consistent result page header based on the proposals of the functional architects.
_Web view:_
The search components' placement inside of the header shall be consistent to the layout of the result page.
_Mobile view:_
Overall the header shall be slimmer. The radius field shall be shorter and the search button placed on the right of it. 

**Out of scope**
Anything else of the result page that is not the header.

**Relation to other Issues**
 #122, #171 

**Acceptance criteria**
_Web view:_
![web](https://user-images.githubusercontent.com/73997608/99708093-a2883680-2a9d-11eb-8f75-208631a33df4.PNG)
_Mobile view:_
![mobil_burgermenu_ohneLogo](https://user-images.githubusercontent.com/73997608/99707923-6ce34d80-2a9d-11eb-906b-c7f9842d9b3b.png)

**Comment by sgrobarek** [comment]
I noticed that if you use e.g. the iphone x size horizontally the view of the header is not correct. The header elements are still ordered wrong. Look at the attached picture.  ![Bildschirmfoto am 2020-11-25 um 19 31 00](https://user-images.githubusercontent.com/64202529/100268593-90067500-2f55-11eb-808b-2a58b654e04f.png)

**Comment by MaiThiD** [comment]
> I noticed that if you use e.g. the iphone x size horizontally the view of the header is not correct. The header elements are still ordered wrong. Look at the attached picture. ![Bildschirmfoto am 2020-11-25 um 19 31 00](https://user-images.githubusercontent.com/64202529/100268593-90067500-2f55-11eb-808b-2a58b654e04f.png)

The new header has not been implemented yet.

**Comment by sgrobarek** [comment]
But it is live on the staging server or not?

**Comment by LeDrieHda** [comment]
This issue has not yet been implemented nor pushed to the staging server. When doing that, I will take into consideration fixing the iPad header as well.

**Comment by sgrobarek** [comment]
Ah okay.

**Comment by FiedlerJan** [comment]
Closed by #263.
