### ISSUE TITLE
Backup enhanced data

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#175]
**Reason (Why?)**
If a website to be crawled is not available during the scraping process, the currently stored data will be discarded. This should not be the case.

**Solution (What?)**
If the scraper does not produce any results, a backup of the corresponding data file (.json) should be created. In the ongoing process a backup should also be made of the corresponding enhanced data file (.json). In this case the corresponding index should not be deleted in the Elastic search.

**Out of scope**
None

**Relation to other Issues**
None

**Acceptance criteria**
If a web page is not available or does not return any data due to an error, the current data of the associated web page will not be changed from the Elastic search.

**Comment by jonas-hda** [comment]
closed with merge of #257
