### ISSUE TITLE
Design proposal of changes to the system architecture for the enhancement process adress to process data from multiple crawlers

### ISSUE THREAD

**Issue by jonas-hda** [hochschule-darmstadt/einander-helfen#176]
**Reason (Why?)**
With the addition of further websites to crawl, the need for an expansion of the enhancement process has arise. The new data does not necessarily conform to the same standards and completion as the currently expected data and thus can require different steps during enhancement. The current approach of having a single data enhancement process for the data from each crawler would lead to duplicate code and a code base that is difficult to maintain.

**Solution (What?)**
Create a design proposal that addresses the enhancement of data from various websites while maintaining scaleability and which allows to perform enhancement steps both specific to the data of individual websites, as well as general enhancement steps applicable to the data of all websites.

**Out of scope**
None

**Relation to other Issues**
#165 Crawlers for various websites 
#174 Remove duplicated posts

**Acceptance criteria**
The proposal for the new software architecture is able to enhance the data of additional websites, supports the enhancement of new data without requiring further changes to the architecture and is implemented.

**Comment by BernhardHumm** [comment]
Please discuss this concept with Armstrong-Arndt, Jamie John (Stud. FBI) jamie.j.armstrong-arndt@stud.h-da.de <mailto:jamie.j.armstrong-arndt@stud.h-da.de>  and Seith, Marvin Oliver (Stud. FBI) marvin.o.seith@stud.h-da.de <mailto:marvin.o.seith@stud.h-da.de>  

I want to avoid duplicated design and implementation work.

 

 

 

 

Von: jonas-hda <notifications@github.com> 
Gesendet: Samstag, 21. November 2020 13:33
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Design proposal of changes to the system architecture for the enhancement process adress to process data from multiple crawlers (#176)

 

Reason (Why?)
With the addition of further websites to crawl, the need for an expansion of the enhancement process has arise. The new data does not necessarily conform to the same standards and completion as the currently expected data and thus can require different steps during enhancement. The current approach of having a single data enhancement process for the data from each crawler would lead to duplicate code and a code base that is difficult to maintain.

Solution (What?)
Create a design proposal that addresses the enhancement of data from various websites while maintaining scaleability and which allows to perform enhancement steps both specific to the data of individual websites, as well as general enhancement steps applicable to the data of all websites.

Out of scope
Final implementation of the design proposal

Relation to other Issues
#165 <https://github.com/hochschule-darmstadt/einander-helfen/issues/165> 
Crawlers for various websites #165 <https://github.com/hochschule-darmstadt/einander-helfen/issues/165> 

Acceptance criteria
The proposal for the new software architecture is able to enhance the data of additional websites, supports the enhancement of new data without requiring further changes to the architecture and can be implemented.

**Comment by jonas-hda** [comment]
changed scope of issue to include implementation of new design rather than creating a new issue for the implementation

**Comment by jonas-hda** [comment]
Closed with the merge of #207
