### ISSUE TITLE
Implementation of missing latitude and longitude at crawling

### ISSUE THREAD

**Issue by sgrobarek** [hochschule-darmstadt/einander-helfen#179]
**Reason (Why?)**
If more than one website is crawled, agile adaption for the crawling coordinates is necessary. Thus a new propsal shall cover the cases once the latitude and longitude data are missing. The feature shall check wether the latitude and longitude data are missing and once it is not crwaled, the feature compute the lat and lon value.

**Solution (What?)**
The new feature gets input fom the crawled data how the data model show it. Now it shall checking wether in the post the geo_location lat and lon are exists or if not the local database shall be requested. If in the database is no entry for location and their lat and lon, the new clean location from the post_struct entry in the post shall be used. For that a geo api, like nominatim must be used to get the lat and lon for the location. If there is no result for the requested api, a new request with the contact from the post is necessary. Is longer no result the organization shall be used for request. If after that there is no result, the current post gets no lat and lon values. For the first three cases the lat and lon values extend the local database and the lat and lon values will add to geo_location.

**Out of scope**
If the geo api deliver no result for the given input, the string can be parsed to extract the single address components.

**Relation to other Issues**

**Acceptance criteria**
The Proposal for the missing latitude and longitude data at crawling is able to deliver results if lat and lon are not explicit indicate on their websites and the geo api returns correct data.

**Comment by BernhardHumm** [comment]
Please separate reason (why) from solution (what). The use of geo APIs is surely no reason but part of the solution.

 

Be much more precise in the description of the solution.

Exactly where in the ETL process will this function be executed? (Relate to BPMN diagram which should have been included in the systems architecture wiki)

Which attributes in the data model will be used for querying the geo API and in which order? (This function will never deal with HTML data but with data in extracted entities)

Which geo APIs are you considering?

 

 

 

 

Von: sgrobarek <notifications@github.com> 
Gesendet: Mittwoch, 25. November 2020 19:23
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Design Proposal for the missing latitude and longitude at crawling (#179)

 

Reason (Why?)
If more than one website is crawled, agile adaption for the crawling coordinates is necessary. Thus a new propsal shall cover the cases once the latitude and longitude data are missing. The feature shall check wether the latitude and longitude data are missing and once it is not crwaled, the feature compute the coordinates with the help of geo api from the address string.

Solution (What?)
The new feature gets the clean crawled data as input then it shall be checking wether in the address data their lat and lon are avaliable. Further it must checked how the address data is displayed in the html code. Then the new fit local storage can be checked wether the address with the lat and lon exists yet. If the address is not available an api for geocoding must be requested. After that a result extend the local database and add the lat lon to the object or if the geocoding api does not deliver a result the object will rejected.

Out of scope
If the geo api deliver no result for the given input, the string can be parsed to extract the single address components.
Anything that is out of scope and shall not be implemented

Relation to other Issues

Acceptance criteria
The Proposal for the missing latitude and longitude data at crawling is able to deliver results if lat and lon are not explicit indicate on their websites and the geo api correct data return.

**Comment by sgrobarek** [comment]
![Geocode_v3-Page-2](https://user-images.githubusercontent.com/64202529/100468960-b5ba8800-30d5-11eb-9f57-298c8853d266.png)
Model for the missing latitude and longitude at crawling

**Comment by BernhardHumm** [comment]
Location / contact / organization are not the output but the input to the geo API.

The Priority 1. Location 2. contact 3. Organization is not clear in this diagram

 

 

 

------------------------------------

Von: sgrobarek <notifications@github.com> 
Gesendet: Freitag, 27. November 2020 17:27
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Design Proposal for the missing latitude and longitude at crawling (#179)

 

 <https://user-images.githubusercontent.com/64202529/100468960-b5ba8800-30d5-11eb-9f57-298c8853d266.png> 
Model for the missing latitude and longitude at crawling

**Comment by sgrobarek** [comment]
@BernhardHumm  i updated the diagram, is it better?

**Comment by BernhardHumm** [comment]
ok

 

 

 

------------------------------------

 

Von: sgrobarek <notifications@github.com> 
Gesendet: Freitag, 27. November 2020 18:15
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Design Proposal for the missing latitude and longitude at crawling (#179)

 

@BernhardHumm <https://github.com/BernhardHumm>  i updated the diagram, is it better?
