### ISSUE TITLE
einander-helfen.org is not working on Internet Explorer 

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#180]
**Describe the bug**
einander-helfen.org is not working on Internet Explorer.

**To Reproduce**
1. Go to 'home'
2. See error

**Expected behavior**
einander-helfen.org should work on all browser.

**Screenshots**
![image](https://user-images.githubusercontent.com/64202398/100022640-d6d45d80-2de3-11eb-9bde-408f9f58ec28.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Internet Explorer
 - Version 11.630.19041.0

**Additional context**
Problem can be solve with polyfill.

**Comment by KaiDrieHda** [comment]
IE is not supported anymore anyways.
