### ISSUE TITLE
Modify data model to include a structured and cleaned up copy of the original data as well as added information

### ISSUE THREAD

**Issue by jonas-hda** [hochschule-darmstadt/einander-helfen#183]
**Reason (Why?)**
To ensure proper sourcing of the original postings from the crawled websites, it is necessary to keep the scraped data as much as possible in their original state that it is found in on the scraped websites. The data is thus often tainted with HTML tags and custom formatting from the scraped website. This causes difficulties during the enhancement process and allows changes for the frontend of the crawled websites to affect the einander-helfen backend process past the crawling.

**Solution (What?)**
Expand the data model to include the original scraped data, as well as a structured representation of the original data. The structured data will be cleaned up and can then be used for our backend processes while the original data can be used for display in the frontend. This way our backend processes are less vulnerable to changes to the frontend of the crawled websites while our frontend maintains proper sourcing of the original postings

**Out of scope**
changing the scrapers according to the data model

**Relation to other Issues**
#174

**Acceptance criteria**
The data model alows the use of cleaned up data for backend processes as well as maintaining the original data state as much as possible for the frontend. The documentation for the data model in both the wiki and the nextcloud have been changed and represent the new data model

**Comment by jonas-hda** [comment]
Updated data model in the wiki and added an example for the json representation
```
Post(JSON Object)
* id: String    [[to be generated from crawled website URL to ensure uniqueness between crawling activities]]
* title: String    
* categories: Array<String>    [[based on tag ontology]]
* location: String    [["Einsatzort"]]
* task: HTML String    [["Aufgabe/Aufgabenfeld", as HTML text from crawled website]]
* target_group: HTML String    [["Zielgruppe"]]
* timing: HTML String    [[e.g., when to start]]
* effort: HTML String    [["Zeitaufwand", e.g., 1 day per week]]
* opportunities: HTML String    [["Möglichkeiten/Chancen, wir bieten an"]]
* organization: HTML String    [[Name, address, phone, email etc. as HTML string from crawled website]]
* contact: HTML String [[Name, address, phone, email etc. of contacting person as HTML string from crawled website]]
* link: URL  [[linked of crawled website]]
* source: string [[ e.g., www.ehrenamtssuche-hessen.de ]]
* image: URL
* geo_location: JSON Object [
                             lat: float,
                             lon: float
                            ]
* post_struct: JSON Object[
			* id: String    [[copy of Post id]]
			* title: String [[copy of Post title, but cleaned up]] 
			* categories: Array<String>    [[based on tag ontology]]
			* location: JSON Object[
						zipcode: integer
						city: String
						street: String
						]
			* task: String    [[copy of Post-attribute, but cleaned up]]
			* target_group: String		[[copy of Post-attribute, but cleaned up]]
			* timing: String	[[copy of Post-attribute, but cleaned up]]
			* effort: String    [[copy of Post-attribute, but cleaned up]]
			* opportunities: String    [[copy of Post-attribute, but cleaned up]]
			* organization: JSON Object[[Name, address, phone, email etc. as cleaned up json]
						name: String
						zipcode: integer
						city: String
						street: String
						phone: integer
						email: string
						]
			* contact: JSON Object[[Name, address, phone, email etc. of contacting person as cleaned up json]
						name: String
						zipcode: integer
						city: String
						street: String
						phone: integer
						email: string
						]
			* link: URL  [[linked of crawled website]]
			* source: string [[ e.g., www.ehrenamtssuche-hessen.de ]]
			* image: URL
			* geo_location: JSON Object[
						lat: float
						lon: float
						]
			*map_address: JSON  [[result of request from map provider, e.g., Google maps or OSM. Use heuristics to determine best source for address, e.g., contact, organization or location]]
			]
```

**Comment by jonas-hda** [comment]
Added new data model to nextcloud
[datamodel-v2.0.pdf](https://github.com/hochschule-darmstadt/einander-helfen/files/5604850/datamodel-v2.0.pdf)

**Comment by BernhardHumm** [comment]
I would think that the representation

geo_location: JSON[                                      lat: float                                      lon:float                                       ]

 

will not allow the geo search in ElasticSearch.

I think you should have lat and lon as attributes.

 

 

------------------------------------

 

 

 

Von: jonas-hda <notifications@github.com> 
Gesendet: Donnerstag, 26. November 2020 21:18
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Modify data model to include a structured and cleaned up copy of the original data as well as added information (#183)

 

Added new data model to nextcloud
datamodel-v2.0.pdf <https://github.com/hochschule-darmstadt/einander-helfen/files/5604850/datamodel-v2.0.pdf>

**Comment by BernhardHumm** [comment]
I would think that the representation

geo_location: JSON[ lat: float   ,  lon:float    ]

 

will not allow the geo search in ElasticSearch.

I think you should have lat and lon as attributes 

 

------------------------------------

 

 

Von: jonas-hda <notifications@github.com> 
Gesendet: Donnerstag, 26. November 2020 20:59
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Modify data model to include a structured and cleaned up copy of the original data as well as added information (#183)

 

Updated data model in the wiki and added an example for the json representation

Post(JSON Object)
 
* id: String    [[to be generated from crawled website URL to ensure uniqueness between crawling activities]]
 
* title: String    
 
* categories: Array<String>    [[based on tag ontology]]
 
* location: String    [["Einsatzort"]]
 
* task: HTML String    [["Aufgabe/Aufgabenfeld", as HTML text from crawled website]]
 
* target_group: HTML String    [["Zielgruppe"]]
 
* timing: HTML String    [[e.g., when to start]]
 
* effort: HTML String    [["Zeitaufwand", e.g., 1 day per week]]
 
* opportunities: HTML String    [["Möglichkeiten/Chancen, wir bieten an"]]
 
* organization: HTML String    [[Name, address, phone, email etc. as HTML string from crawled website]]
 
* contact: HTML String [[Name, address, phone, email etc. of contacting person as HTML string from crawled website]]
 
* link: URL  [[linked of crawled website]]
 
* source: string [[ e.g., www.ehrenamtssuche-hessen.de <http://www.ehrenamtssuche-hessen.de>  ]]
 
* image: URL
 
* geo_location: JSON Object [
 
                             lat: float,
 
                             lon: float
 
                            ]
 
* post_struct: JSON Object[
 
                       * id: String    [[copy of Post id]]
 
                       * title: String [[copy of Post title, but cleaned up]] 
 
                       * categories: Array<String>    [[based on tag ontology]]
 
                       * location: JSON Object[
 
                                              zipcode: integer
 
                                              city: String
 
                                              street: String
 
                                              ]
 
                       * task: String    [[copy of Post-attribute, but cleaned up]]
 
                       * target_group: String         [[copy of Post-attribute, but cleaned up]]
 
                       * timing: String       [[copy of Post-attribute, but cleaned up]]
 
                       * effort: String    [[copy of Post-attribute, but cleaned up]]
 
                       * opportunities: String    [[copy of Post-attribute, but cleaned up]]
 
                       * organization: JSON Object[[Name, address, phone, email etc. as cleaned up json]
 
                                              name: String
 
                                              zipcode: integer
 
                                              city: String
 
                                              street: String
 
                                              phone: integer
 
                                              email: string
 
                                              ]
 
                       * contact: JSON Object[[Name, address, phone, email etc. of contacting person as cleaned up json]
 
                                              name: String
 
                                              zipcode: integer
 
                                              city: String
 
                                              street: String
 
                                              phone: integer
 
                                              email: string
 
                                              ]
 
                       * link: URL  [[linked of crawled website]]
 
                       * source: string [[ e.g., www.ehrenamtssuche-hessen.de <http://www.ehrenamtssuche-hessen.de>  ]]
 
                       * image: URL
 
                       * geo_location: JSON Object[
 
                                              lat: float
 
                                              lon: float
 
                                              ]
 
                       *map_address: JSON  [[result of request from map provider, e.g., Google maps or OSM. Use heuristics to determine best source for address, e.g., contact, organization or location]]
 
                       ]

**Comment by jonas-hda** [comment]
> 
> I would think that the representation geo_location: JSON[ lat: float , lon:float ] will not allow the geo search in ElasticSearch. I think you should have lat and lon as attributes

In the current implementation, our data is already uploaded to elastic search in a json conform format. The following is an example of the geo_location of a post when it gets accesses in write_to_elastic() in elastic.py and send to the elastic search server according to the old data model: 
'geo_location':{
      'lat':51.0667,
      'lon':8.8
   },
which is identical to the representation of geo_location in the new data model format. geo_location therefore has always been in a jsonobject conform format, but now it is explicitly stated in our datamodel that this is intentional and not just happenstance.

**Comment by BernhardHumm** [comment]
OK, thanks!

 

 

 

Von: jonas-hda <notifications@github.com> 
Gesendet: Samstag, 28. November 2020 16:56
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Comment <comment@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Modify data model to include a structured and cleaned up copy of the original data as well as added information (#183)

 

I would think that the representation geo_location: JSON[ lat: float , lon:float ] will not allow the geo search in ElasticSearch. I think you should have lat and lon as attributes

In the current implementation, our data is already uploaded to elastic search in a json conform format. The following is an example of the geo_location of a post when it gets accesses in write_to_elastic() in elastic.py and send to the elastic search server according to the old data model:
'geo_location':{
'lat':51.0667,
'lon':8.8
},
which is identical to the representation of geo_location in the new data model format. geo_location therefore has always been in a jsonobject conform format, but now it is explicitly stated in our datamodel that this is intentional and not just happenstance.

**Comment by jonas-hda** [comment]
removed image from datamodel and example in the wiki.
```
Post(JSON Object)
* id: String    [[to be generated from crawled website URL to ensure uniqueness between crawling activities]]
* title: String    
* categories: Array<String>    [[based on tag ontology]]
* location: String    [["Einsatzort"]]
* task: HTML String    [["Aufgabe/Aufgabenfeld", as HTML text from crawled website]]
* target_group: HTML String    [["Zielgruppe"]]
* timing: HTML String    [[e.g., when to start]]
* effort: HTML String    [["Zeitaufwand", e.g., 1 day per week]]
* opportunities: HTML String    [["Möglichkeiten/Chancen, wir bieten an"]]
* organization: HTML String    [[Name, address, phone, email etc. as HTML string from crawled website]]
* contact: HTML String [[Name, address, phone, email etc. of contacting person as HTML string from crawled website]]
* link: URL  [[linked of crawled website]]
* source: string [[ e.g., www.ehrenamtssuche-hessen.de ]]
* geo_location: JSON Object [
                             lat: float,
                             lon: float
                            ]
* post_struct: JSON Object[
			* id: String    [[copy of Post id]]
			* title: String [[copy of Post title, but cleaned up]] 
			* categories: Array<String>    [[based on tag ontology]]
			* location: JSON Object[
						zipcode: integer
						city: String
						street: String
						]
			* task: String    [[copy of Post-attribute, but cleaned up]]
			* target_group: String		[[copy of Post-attribute, but cleaned up]]
			* timing: String	[[copy of Post-attribute, but cleaned up]]
			* effort: String    [[copy of Post-attribute, but cleaned up]]
			* opportunities: String    [[copy of Post-attribute, but cleaned up]]
			* organization: JSON Object[[Name, address, phone, email etc. as cleaned up json]
						name: String
						zipcode: integer
						city: String
						street: String
						phone: integer
						email: string
						]
			* contact: JSON Object[[Name, address, phone, email etc. of contacting person as cleaned up json]
						name: String
						zipcode: integer
						city: String
						street: String
						phone: integer
						email: string
						]
			* link: URL  [[linked of crawled website]]
			* source: string [[ e.g., www.ehrenamtssuche-hessen.de ]]
			* geo_location: JSON Object[
						lat: float
						lon: float
						]
			*map_address: JSON  [[result of request from map provider, e.g., Google maps or OSM. Use heuristics to determine best source for address, e.g., contact, organization or location]]
			]
```
