### ISSUE TITLE
Processing (Display) null values of location data on the result page

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#187]
**Reason (Why?)**
The rendered DOM of the location data on the result page does not always fit the current layout yet. Null values result in " ," which makes the result look faulty.

Example
![image](https://user-images.githubusercontent.com/64202398/100398063-44cf8d80-304d-11eb-8316-b19a885ed89a.png)

**Solution (What?)**
Null values should not result in " ," and instead be ignored. This should be implemented for the result selection (left side) and the detail view (right side).

**Out of scope**
/

**Relation to other Issues**
/

**Acceptance criteria**
The rendered page/DOM does not contain unnecessary " ," Strings for the location data and instead only shows the available information. (e. g. Berlin)

**Comment by FiedlerJan** [comment]
This will already be done in the backend. This is a bug which will be fixed while redoing the data model of gute-tat.

**Comment by BernhardHumm** [comment]
These are the original HTML tables on https://www.gute-tat.de/helfen/ehrenamtliches-engagement/projekte-berlin/ 



Exactly these HMTL tables should be displayed in einander-helfen.de: the first one under Location (Einsatzort), the second one under Contact (Ansprechpartner)

No interpretation by the backend!

 

 

 

 

------------------------------------

Von: MaiThiD <notifications@github.com> 
Gesendet: Freitag, 27. November 2020 12:14
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Processing (Display) null values of location data on the result page (#187)

 

Reason (Why?)
The rendered DOM of the location data on the result page does not always fit the current layout yet. Null values result in " ," which makes the result look faulty.

Example
 <https://user-images.githubusercontent.com/64202398/100398063-44cf8d80-304d-11eb-8316-b19a885ed89a.png> 

Solution (What?)
Null values should not result in " ," and instead be ignored. This should be implemented for the result selection (left side) and the detail view (right side).

Out of scope
/

Relation to other Issues
/

Acceptance criteria
The rendered page/DOM does not contain unnecessary " ," Strings for the location data and instead only shows the available information. (e. g. Berlin)
