### ISSUE TITLE
Remove logos from ResultPage

### ISSUE THREAD

**Issue by DianaPankratz** [hochschule-darmstadt/einander-helfen#189]
**Reason (Why?)**
The logo of the website offering the post decimates the space of the title in a list item and the details view, especially in the mobile view. Moreover after crawling new websites the sizes of the logos might be different and hard to handle. 

**Solution (What?)**
The logos should be removed completley.

**Out of scope**
Any other page that is not the result page.

**Relation to other Issues**
#122 

**Acceptance criteria**
1. No logos in the post list
2. No logos in details view

**Comment by BernhardHumm** [comment]
We have decided to leave out logos. So:

1.	Remove from data model
2.	Do not set in backend
3.	Do not use anywhere in frontend

 

 

 

 

 

Von: DianaPankratz <notifications@github.com> 
Gesendet: Sonntag, 29. November 2020 13:17
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Remove logos from post list and only show them in details view (#189)

 

Reason (Why?)
The logo of the website offering the post decimates the space of the title in a list item, especially in the mobile view. Moreover after crawling new websites the sizes of the logos might be different and hard to handle.

Solution (What?)
The logos in the list items should be removed. The logos in the details view could be removed, too, or it must be ensured that they don't cut off the title.

Out of scope
None

Relation to other Issues
None

Acceptance criteria

1.	No logos in the post list
2.	No logos in details view or logos that don't cut off titles
