### ISSUE TITLE
Category (Tag) Search

### ISSUE THREAD

**Issue by BernhardHumm** [hochschule-darmstadt/einander-helfen#21]
**Reason (Why?)**
The user shall be able  to conveniently search for categories (tags)

**Solution (What?)**

This features requires frontend  and backend activities 

***Backend***

Basis for the category search is the tag ontology file tags-einander-helfen.csv (see Moodle course). It lists all tags for categorizing posts. This ontology file needs to be extended when new web sites are crawled or when new tags appear on the crawled sites.

In the semantic enhancement part of the ETL process, this file is used for normalizing tags (category entries in posts). Synonyms are converted to the main tag, e.g., "EDV" -> "Computer". 
Tags appearing in posts which are not yet in the ontology shall be logged to a file new_tags.txt

***Frontend***

The tag ontology file tags-einander-helfen.csv shall be used in the frontend for autocompleting search inputs by users. When the user starts typing, e.g., "co" then "Computer" will be suggested.
Also synonyms shall be used, e.g., when tying "ed" then "Computer (EDV)" will be suggested.
Autocompleting an entry will automatically start the search. 
The autocompleted tag will be used in the category search (search for the category field in ElasticSearch entries).
Improvement(?):  full-text search. This will find hits where the term is mentioned in another text field. Then entries with a match in field categories shall be ranked higher than full text search matches in other text fields.

The user may add additional search tags. They can be used connected using SHOULD or MUST (to be discussed)

When the user does not select an autocomplete suggestion then a full-text search shall be performed. 

**Not doing**

**Relation to other Issues**

**Acceptance criteria**

**Comment by FiedlerJan** [comment]
@marvinseith @JamieArmstrongArndt @andresesam @BaderChouaib I think this issue is done, isn't it?

**Comment by BaderChouaib** [comment]
I would say so from the frontend point of view

**Comment by marvinseith** [comment]
Can be closed. Will open a new issue for the tag ranking with the points that are open for next semester students.
