### ISSUE TITLE
add crawler for ein-jahr-freiwillig.de

### ISSUE THREAD

**Issue by sgrobarek** [hochschule-darmstadt/einander-helfen#216]
**Reason (Why?)**
To extend our current database on posts we need to have more crawling websites. 

**Solution (What?)**
Crawling the "ein-jahr-freiwillig.de" website to achieve more results at searching posts at einander-helfen.org.

**Out of scope**
Anything that is no text.

**Relation to other Issues**
This crawling procedure is related to the crawler of "gutetat" and "weltwärts".

**Comment by jonas-hda** [comment]
closed with merge of #230
