### ISSUE TITLE
Enhance marker clusters

### ISSUE THREAD

**Issue by DianaPankratz** [hochschule-darmstadt/einander-helfen#219]
**Reason (Why?)**
1. When the user selects a post whose pin is inside of a marker cluster he can't see the destination of the pin as the map does not open the cluster. 
2. When the user opens a marker cluster the map does not focus or zoom on the cluster.

**Solution (What?)**
1. If the user opens a post whose pin is in a marker cluster the cluster should open itself. The map should zoom into the pin and focus it.
2. If the user opens a marker cluster the map should zoom correctly to see all pins of the cluster. The middle of the opened cluster should be the center of the map

**Out of scope**
Anything that is not the result page.

**Relation to other Issues**
/

**Acceptance criteria**
See solution

**Comment by KaiDrieHda** [comment]
Duplicate. See #330
