### ISSUE TITLE
Develop a concept for integrating the international results from weltwaerts.de 

### ISSUE THREAD

**Issue by LeDrieHda** [hochschule-darmstadt/einander-helfen#224]
**Reason (Why?)**
The usefulness of einander-helfen.org depends on the versatility of the results.

**Solution (What?)**
To be able to offer international, as well as national results, we need to develop a concept for including the international results crawled from weltwaerts.de
The user should be able to find posts in different countries and filter for the country they want to find posts in.
Perform a research on how other websites implemented similar requirements.

**Out of scope**

**Relation to other Issues**
#169, #122 

**Acceptance criteria**

**Comment by MaiThiD** [comment]
The presentation is in the nextcloud: EinanderHelfen > Layout > international_results
