### ISSUE TITLE
Modify categories field in ES from dictionary representation to array

### ISSUE THREAD

**Issue by BaderChouaib** [hochschule-darmstadt/einander-helfen#23]
**Reason (Why?)**
Currently the categories field is implemented as dictionary with keys being "Cat1", "Cat2" etc.. 
![grafik](https://user-images.githubusercontent.com/25898717/83334828-64a61480-a2a9-11ea-99aa-1ba895377039.png)

This is hard to maintain and becomes problematic to access via queries.

**Solution (What?)**
Modify this dictionary representaiton to a simple array representation with string terms that relate to the categories. 

**Relation to other Issues**
Might aid #21 in querying category items

**Acceptance criteria**
Content of categories field should be easy to query without key:value representation

**Comment by BernhardHumm** [comment]
Please adhere to the common data model which is compulsory for cliend and server

https://github.com/hochschule-darmstadt/einander-helfen/wiki/System-Architecture

 

Then, such an error cannot happen. 

 

------------------------------------

 

Von: BaderChouaib [mailto:notifications@github.com] 
Gesendet: Samstag, 30. Mai 2020 19:14
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Modify categories field in ES from dictionary representation to array (#23)

 

Reason (Why?)
Currently the categories field is implemented as dictionary with keys being "Cat1", "Cat2" etc..
 <https://user-images.githubusercontent.com/25898717/83334828-64a61480-a2a9-11ea-99aa-1ba895377039.png> 

This is hard to maintain and becomes problematic to access via queries.

Solution (What?)
Modify this dictionary representaiton to a simple array representation with string terms that relate to the categories.

Relation to other Issues
Might aid #21 <https://github.com/hochschule-darmstadt/einander-helfen/issues/21>  in querying category items

Acceptance criteria
Content of categories field should be easy to query with key:value representation

**Comment by marvinseith** [comment]
Already discussed and "fixed". Elastic automatically changes the Array Input of the categories to numbered inputs. The queries are not affected and can be performed for every category.
