### ISSUE TITLE
add_crawler_for_bundesfreiwilligendienst.de

### ISSUE THREAD

**Issue by sgrobarek** [hochschule-darmstadt/einander-helfen#237]
Reason (Why?)
To extend our current database on posts we need to have more crawling websites.

Solution (What?)
Crawling the "www.bundesfreiwilligendienst.de" website to achieve more results at searching posts at einander-helfen.org.

Out of scope
Anything that is no text.

Relation to other Issues
This crawling procedure is related to all currently exists crawler.

**Comment by jonas-hda** [comment]
closed with merge of #241
