### ISSUE TITLE
Location and range selection

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#24]
**Reason (Why?)**
The user shall be able to select a location and a range.

**Solution (What?)**
It contains two components:

1. A location input field: You should be able to enter the name or PLZ of a location. While typing the field should show 10 results which are based on the input and a specified rank.
2. A range input field: You should be able to select between 10km, 25km, 50km, everywhere.

**Not doing**
The creation of the csv file, the location field is based on and the algorithm which communicates with ES.

**Relation to other Issues**
#13 Implementation of location based search: Gives the context to this issue.

**Acceptance criteria**
The location input field shows the correct locations.
The range input field contains: 10km, 25km, 50km, everywhere.

**Comment by BernhardHumm** [comment]
Consider the detailed specification of location based search in #13:

 

To implement location based search there are two ends to be considered: 

(a) location search input by user 

(b) location information in data

 

 

Ad (a) location search input by user:

 

There are two input fields for location information: 

1.      location (text input field with autosuggest) 

2.      range (dropdown: e.g., 10km, 25km, 50km, everywhere)

 

In the location text input field, the user shall be able to enter all cities or PLZ (ZIP codes) in Germany . The AutoSuggest shall allow selecting one. 

Data basis, e.g. https://www.suche-postleitzahl.org/downloads

Suggestion: load the city names and PLZ on the start of the web app (size shouldn’t be too large) and use in autoSuggest.

 

The data for AutoSuggest must contain the following attributes:

*        name, e.g., „Friedberg(Hessen)“

*        ZIP code: e.g., 61169

*        lat, lon

*        rank

 

Name and ZIP are used for autoSuggest and are displayed. E.g. 

*        entering “Fried” -> autoSuggest “61169 Friedberg (Hessen)

*        entering “611” -> autoSuggest “61169 Friedberg (Hessen)

 

lat, lon are used for querying the ElasticSearch server.

rank reveals the size of city (area) and is used for selecting autosuggest entries if there are too many matches (see below).

 

Special case: Cities with several ZIP codes, e.g., Frankfurt. 

Then, an additional entry for all ZIP codes shall be suggested, 

e.g., entering “Frankf” -> autsuggest:

*        Frankfurt am Main (alle)

*        Frankfurt (Oder) (alle)

*        60306 Frankfurt am Main

*        60314 Frankfurt am Main

*        15230 Frankfurt (Oder)

*        15232 Frankfurt (Oder)

 

The lat, lon for for an aggregated entry like “Frankfurt am Main (alle)” shall be in the center of the city.

 

AutoSuggest shall be limited to 10 entries. If there are more candidates matching the search string, a selection shall be made based on relevance (rank of entry reveals size of city) and diversity (e.g., regional difference).  A good example is Frankfurt above: various examples of Frankfurt am Main and Frankfurt (Oder) are displayed. 

 

Browser location information: 

If the browser of the used contains location information, then location text field shall be initialized with this location (range initialized with “everywhere)

 

 

 

Ad (b) location information in data

 

Each post in the data base shall contain lat, lon. Finding a suitable lat, lon for each post is part of the semantic enrichment process in ETL.

During search, the Geo-distance query feature of ElasticSearch can be used:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-distance-query.html 

Here, the lat/lon information from the autoSuggest of the location search input and the range information by the user are used as query inputs and the lat/lon information of the data is matched. 

 

 

 

 

------------------------------------

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Sonntag, 31. Mai 2020 16:04
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Location and range selection (#24)

 

Reason (Why?)
The user shall be able to select a location and a range.

Solution (What?)
It contains two components:

1.	A location input field: You should be able to enter the name or PLZ of a location. While typing the field should show 10 results which are based on the input and a specified rank.
2.	A range input field: You should be able to select between 10km, 25km, 50km, everywhere.

Not doing
The creation of the csv file, the location field is based on and the algorithm which communicates with ES.

Relation to other Issues
#13 <https://github.com/hochschule-darmstadt/einander-helfen/issues/13>  Implementation of location based search: Gives the context to this issue.

Acceptance criteria
The location input field shows the correct locations.
The range input field contains: 10km, 25km, 50km, everywhere.
