### ISSUE TITLE
Scroll to the selected list item in mobile ResultPage

### ISSUE THREAD

**Issue by DianaPankratz** [hochschule-darmstadt/einander-helfen#242]
**Reason (Why?)**
In the mobile version the list should scroll to the selected list item (post) so it is on the top of the list.

**Solution (What?)**
Only the list should scroll, not the whole screen. That means if the map is visible at the top of the screen it should not move after selecting a post. Only the list itself should scroll.

**Out of scope**
Any other page that is not the result page. The Webversion of the page.

**Relation to other Issues**
#76

**Acceptance criteria**
* Click on a list item to select it. The list item should be shown at the top of the list.
* Open the map an scroll so you can see a part of the map an a part of the list. Then select a post. Only the list should scroll to the list item but the map should stay visible and unmoved.

**Comment by theErikss0n** [comment]
This Issue was resolved by #495
