### ISSUE TITLE
Implement the layout for integrating the search for international results 

### ISSUE THREAD

**Issue by LeDrieHda** [hochschule-darmstadt/einander-helfen#244]
**Reason (Why?)**
The usefulness of einander-helfen.org depends on the versatility of the results. We want to be able to offer international, as well as national, results.

**Solution (What?)**
On the home and result pages both in web and mobile view the pin icon to the left of the location search bar should be replaced by the german flag, with a small triangle next to it to indicate it being a dropdown. 
When clicking on it, a dropdown with one option "Weltweit" with a globe icon next to it should expand. 
When clicking on "Weltweit" the dropdown collapses again, the german flag icon is switched to the globe icon in the location search bar. The text inside the location search bar changes from "Ort oder PLZ" to "Land oder Kontinent", the radius field gets grayed out/disabled.  

**Out of scope**
Only the layout should be implemented here. The actual filtering of the posts/searching for international results will be implemented with another (backend) issue. 

**Relation to other Issues**
#224 
#247 implements the international search (backend).

**Acceptance criteria**
_Home page web view:_
![image](https://user-images.githubusercontent.com/73997608/102511195-c7fe6500-4088-11eb-9528-ecf8e1454876.png)
![image](https://user-images.githubusercontent.com/73997608/102511242-d77dae00-4088-11eb-9219-091af15d3a86.png)

_Result page web view:_
![image](https://user-images.githubusercontent.com/73997608/102511292-e5cbca00-4088-11eb-8c0a-b9f2ad8a13aa.png)
![image](https://user-images.githubusercontent.com/73997608/102511301-e95f5100-4088-11eb-806c-1784112ca41f.png)

_Result page mobile view:_
![image](https://user-images.githubusercontent.com/73997608/102511367-fd0ab780-4088-11eb-97f3-6bf18fe016f5.png) ![image](https://user-images.githubusercontent.com/73997608/102511381-01cf6b80-4089-11eb-85a7-d8a0dab10321.png)

**Comment by DianaPankratz** [comment]
* Correct select size in tablet view
* Edit smartphone header
* Don't use radius in interntaional search

**Comment by FiedlerJan** [comment]
* Add the image sources for germany and international to the imprint.
