### ISSUE TITLE
Change the displayed source url

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#245]
**Reason (Why?)**
The displayed source url should be displayed on all posts with the same syntax.

**Solution (What?)**
Change the following texts in source:
https://ein-jahr-freiwillig.de to www.ein-jahr-freiwillig.de
https://www.weltwaerts.de to www.weltwaerts.de

**Out of scope**
/

**Relation to other Issues**
/

**Acceptance criteria**
Displayed text has been changed.

**Comment by jonas-hda** [comment]
closed with the merge of #246
