### ISSUE TITLE
Predefine location csv file

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#25]
**Reason (Why?)**
The location and range search shall use predefined data.

**Solution (What?)**
An python script which takes a PLZ-location csv file and adds needed data.
The script should add lat, lon and a rank based on the size of the city.

**Not doing**
The frontend implementation and the algorithm which communicates with ES.

**Relation to other Issues**
#13 Implementation of location based search: Gives the context to this issue.

**Acceptance criteria**
The created csv output file contains PLZ,name,lat,lon,rank for each location.

**Comment by BernhardHumm** [comment]
Consider special case of cities with several PLZ in one city. See my detailed specification in #13:

 

The data for AutoSuggest must contain the following attributes:

*        name, e.g., „Friedberg(Hessen)“

*        ZIP code: e.g., 61169

*        lat, lon

*        rank

 

Name and ZIP are used for autoSuggest and are displayed. E.g. 

*        entering “Fried” -> autoSuggest “61169 Friedberg (Hessen)

*        entering “611” -> autoSuggest “61169 Friedberg (Hessen)

 

lat, lon are used for querying the ElasticSearch server.

rank reveals the size of city (area) and is used for selecting autosuggest entries if there are too many matches (see below).

 

Special case: Cities with several ZIP codes, e.g., Frankfurt. 

Then, an additional entry for all ZIP codes shall be suggested, 

e.g., entering “Frankf” -> autsuggest:

*        Frankfurt am Main (alle)

*        Frankfurt (Oder) (alle)

*        60306 Frankfurt am Main

*        60314 Frankfurt am Main

*        15230 Frankfurt (Oder)

*        15232 Frankfurt (Oder)

 

The lat, lon for for an aggregated entry like “Frankfurt am Main (alle)” shall be in the center of the city.

 

 

 

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Sonntag, 31. Mai 2020 16:11
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Predefine location csv file (#25)

 

Reason (Why?)
The location and range search shall use predefined data.

Solution (What?)
An python script which takes a PLZ-location csv file and adds needed data.
The script should add lat, lon and a rank based on the size of the city.

Not doing
The frontend implementation and the algorithm which communicates with ES.

Relation to other Issues
#13 <https://github.com/hochschule-darmstadt/einander-helfen/issues/13>  Implementation of location based search: Gives the context to this issue.

Acceptance criteria
The created csv output file contains PLZ,name,lat,lon,rank for each location.

**Comment by jschurse** [comment]
Implemented and merged
