### ISSUE TITLE
Fix existing backend unit tests

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#255]
**Describe the bug**
Currently there is no consistent way to execute all python unit tests without an error.

**To Reproduce**
1. Go to '(einander-helfen)/etl'
2. Execute 'python3 install -r requirements'
3. Execute 'python3 -m unittest'

**Expected behavior**
All python unit tests should be executed without an error that does not come from the created code.

**Additional context**
There is an pythonpath/directory naming issue.

**Comment by jonas-hda** [comment]
closed with merge of #256
