### ISSUE TITLE
Update npm dependencies

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#258]
**Reason (Why?)**
The last update of the npm dependencies was 6 months ago. Currently there are some buggy elements in the frontend that might correspond with the versions of the npm modules.

**Solution (What?)**
Update all npm dependencies to the currently newest version.

**Out of scope**
None

**Relation to other Issues**
None

**Acceptance criteria**
The package.json in the app directory contains the latest version of the npm modules.

**Comment by jonas-hda** [comment]
closed with the merge of #259
