### ISSUE TITLE
ResultPage: Posts are shown incorrectly on detailed view for all result pages after 1

### ISSUE THREAD

**Issue by BaderChouaib** [hochschule-darmstadt/einander-helfen#26]
**Describe the bug**
When viewing results on resultPage only the posts on the first page of results are displayed correctly after getting selected. For every page after page 1 the posts displayed on the detailed view on the right side are actually posts from the first page of results.

**To Reproduce**
Query something via searchbar to get routed at resultPage and ensure that the results exceed the maximal amount displayed on page 1 of results. When viewing posts at page 2 of results you should realize a mismatch between the detailed view of the posts on the right side and the selected posts on the left side

**Expected behavior**
Detailed view of posts for every page you select on pages >1 should be shown correctly

**Screenshots**
![grafik](https://user-images.githubusercontent.com/25898717/83440950-095d5900-a446-11ea-9a03-fedce4a7ca5f.png)

**Comment by MaiThiD** [comment]
fixed and merged
