### ISSUE TITLE
ResultPage: Not responsive

### ISSUE THREAD

**Issue by andresesam** [hochschule-darmstadt/einander-helfen#27]
**Describe the bug**
The resultpage itself is not responsive. User which want to interact with the webpage via tablet or phone, won't be able to deal with the given offers.

**To Reproduce**
Feed the homepage's searchbar with some input and route to the resultpage. Press F12 to open the developer tools and change the layout to responsive.

**Expected behavior**
The resultpage should be displayed responsive to get a good user experience.

**Screenshots**
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6/7]
![image](https://user-images.githubusercontent.com/39090774/83499253-5af4fa80-a4bd-11ea-9d33-0588d01ebfb6.png)

**Comment by jschurse** [comment]
Partially fixed by https://github.com/hochschule-darmstadt/einander-helfen/commit/72460e8fb7e0ac260c3767f3885712f12399f3d4 
I used css grids to fix the layout: https://github.com/hochschule-darmstadt/einander-helfen/blob/72460e8fb7e0ac260c3767f3885712f12399f3d4/app/src/views/ResultPage.vue#L273-L304

But the search bar is still not mobile usable

**Comment by jschurse** [comment]
@sgrobarek did you have a look at this issue and what was already done,  before you pushed and merged?

In your layout changes the map and post details are at the bottom of the page:
![image](https://user-images.githubusercontent.com/12964877/84871146-739a0e80-b080-11ea-9a01-9865ccea1490.png)


If there are less posts a huge empty space is being shown:
![image](https://user-images.githubusercontent.com/12964877/84871027-58c79a00-b080-11ea-8816-c4d25fe267e8.png)

**Comment by sgrobarek** [comment]
@sgrobarek did you have a look at this issue and what was already done, before you pushed and merged?

@jschurse sry, saw that after my work was done. hope everything is okay :S

**Comment by jschurse** [comment]
Implemented and merged
