### ISSUE TITLE
Displayed title of the pin on the map is sometimes cut off

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#273]
**Describe the bug**
Displayed title of the pin on the map is sometimes cut off.

**To Reproduce**
1. Go to 'resultpage'
2. Click on a pin with a long title.

**Expected behavior**
The title should not be cut off

**Screenshots**
Desktop version:
![image](https://user-images.githubusercontent.com/64202398/105609704-58784580-5dab-11eb-88ab-57e9a58cbd71.png)
![image](https://user-images.githubusercontent.com/64202398/105609714-675ef800-5dab-11eb-9eb5-94e01c78d06b.png)

mobile:
![image](https://user-images.githubusercontent.com/64202398/105345382-7e072280-5be4-11eb-8575-20f9e98f46e8.png)

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**
/

**Comment by KaiDrieHda** [comment]
Duplicate. See #327
