### ISSUE TITLE
implement frontend logic for search for international results

### ISSUE THREAD

**Issue by jonas-hda** [hochschule-darmstadt/einander-helfen#274]
**Reason (Why?)**
With the addition of of international search results, functionality is needed to integrate them into the frontend.

**Solution (What?)**
* Create a mechanism that can be used to determine if the national search or the new query for international search should be used (for example a status flag) (@sgrobarek)
* Create a query for all available countries(for auto-suggest) (@AndreBruecke & @DanielKraft)
* Create a query for international search results (@FiedlerJan)
* Create a query for national search results (@FiedlerJan)

**Comment by jonas-hda** [comment]
possible solution for all countries in posts:
https://stackoverflow.com/questions/40381339/how-to-do-an-elasticsearch-select-distinct

**Comment by DianaPankratz** [comment]
* Store international value in route (@sgrobarek @FiedlerJan)
* Check missing results (@FiedlerJan)
