### ISSUE TITLE
Searchbar on result page and dots of carousel on home page are asymmetric

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#276]
**Describe the bug**
On the result page in web layout and mobile layout the lower corners of the search bar are shaped differently than the upper corners. In tablet layout (between 600px and 959px) the search bar is symmetric (see screenshots below).
Also the three dots below the picture carousel on the home page are not in the middle of the page, but rather slightly to the right.

**To Reproduce**
Steps to reproduce the behavior of searchbar:
1. Go to result page
2. Adjust window size to max. 599px or min. 960px width
3. See error of search bar

Steps to reproduce the behavior of dots:
1. Go to home page
2. See error of dots

**Expected behavior**
The searchbar should be symmetrical, like it is in the tablet layout, but in all window sizes.
The three dots below the picture carousel should be centered.

**Screenshots**
_Search bar web view:_
![image](https://user-images.githubusercontent.com/73997608/105896621-56b2ba00-6017-11eb-9b44-3489c61ab0cf.png)
_Search bar in mobile view:_
![image](https://user-images.githubusercontent.com/73997608/105896727-7813a600-6017-11eb-914a-a1f112d53719.png)

_For comparison: search bar in tablet view is symmetrical_
![image](https://user-images.githubusercontent.com/73997608/105896802-98436500-6017-11eb-9f4a-e307fe77d08a.png)

_Three dots slightly to the right_
![image](https://user-images.githubusercontent.com/73997608/105896508-28cd7580-6017-11eb-807c-ea3e7eea1cc4.png)

**Desktop:**
- all

**Smartphone:**
- all

**Comment by xcaverxiii** [comment]
This should be fixed by pr #302 and #333.
