### ISSUE TITLE
Replace the es-query-builder

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#277]
**Reason (Why?)**
The [es-query-builder](https://github.com/hochschule-darmstadt/es-query-builder) was developed for the openartbrowser. It does not contain all functions needed to control the elasticsearch. Also there are free libraries on the internet which have the same funtions.

**Solution (What?)**
Remove the es-query-builder npm package from the frontend and replace it with another package which meets the expectations. Search the internet for available packages. Refactor the code to make the queries work with the new npm package.

**Out of scope**
None

**Relation to other Issues**
None

**Acceptance criteria**
The elasticsearch queries are reworked.

**Comment by jschurse** [comment]
The openartbrowser project is currently switching the query-builder for the [bodybuilder](https://www.npmjs.com/package/bodybuilder) package: https://github.com/hochschule-darmstadt/openartbrowser/issues/435
Maybe this would be usefull here too.
