### ISSUE TITLE
Check the code with a linter

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#278]
**Reason (Why?)**
Over time, the code has expanded greatly and has been revised. Among other things, code fragments have remained that are no longer used. These and other points degrade the code quality and thus reduce the maintainability of the code.

**Solution (What?)**
Use a linter like SonarLint to find the problems and fix them if fixing the problem is considered reasonable.

**Out of scope**
None

**Relation to other Issues**
None

**Acceptance criteria**
The code quality is at a higher level than before and the functionality is the same as before.

**Comment by jonas-hda** [comment]
taking care of the backend part of this issue, working branch is #278/Check_the_code_with_a_linter

**Comment by jonas-hda** [comment]
closed with merge of #282
