### ISSUE TITLE
Some titles are not displayed correctly on resultpage

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#283]
**Describe the bug**
Some titles are not displayed correctly

**To Reproduce**
1. Go to 'resultpage'
2. Search for 'Kindergarten PhorMinis&Grundschule Phorms Campus Berlin Süd'
3. Click on post

**Expected behavior**
Should be displayed correctly
![image](https://user-images.githubusercontent.com/64202398/106898586-aae32b80-66f4-11eb-9791-a3f1ca0f023d.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/64202398/106897759-a5d1ac80-66f3-11eb-8efb-8e1eb374ea06.png)
![image](https://user-images.githubusercontent.com/64202398/106898267-41631d00-66f4-11eb-9844-a5be36faaf3c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 88.0.4324.104

**Additional context**
/

**Comment by jonas-hda** [comment]
The post for Kindertagesstätte is the frontend failing to properly display the <br/>. The original post contains the <br/> and thus it gets handed off to the frontend.

The post for Kindergarten seems to be a backend issue as the &amp is just a '&' on the original post. I will look into the backend part of this issue

**Comment by jonas-hda** [comment]
The reported behaviour is 2 separate bugs which are now covered by #287 and #288 

This is issue is therefore closed.
