### ISSUE TITLE
Some titles are not displayed correctly on resultpage

### ISSUE THREAD

**Issue by jonas-hda** [hochschule-darmstadt/einander-helfen#287]
**Describe the bug**
Some posts titles are not displayed correctly

**To Reproduce**
Reproducing this error might be tricky as it is based on the crawled data and the post might no longer exist on the original site.
1. Go to 'resultpage'
2. Search for 'Internationale Strolche' and location 'Köln'
3. Click on post

Alternatively:
Insert a post with a <br/> tag in the title into your local elasticsearch database, then repeat the above steps for your local instance of the application.

**Expected behavior**
The <br/> tag should not be displayed but instead properly interpreted as a linebreak.

**Screenshots**
Screenshot of the post as it is displayed on einander-helfen.org/:
![image](https://user-images.githubusercontent.com/64202398/106898267-41631d00-66f4-11eb-9844-a5be36faaf3c.png)

Screenshot of the original post:
![Page](https://user-images.githubusercontent.com/74006324/107757353-ba322c80-6d25-11eb-8b42-924cc0a7aff5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 88.0.4324.104

 - OS: Windows 10
 - Browser Firefox
 - Version 85.0.2 (64-Bit)

**Additional context**
This Issue is part of the original issue #283

Sourcecode of the original posting:
[sourcecode.txt](https://github.com/hochschule-darmstadt/einander-helfen/files/5971092/sourcecode.txt)

JSON Data for the Post as delivered by the backend:
[Strolche_post.txt](https://github.com/hochschule-darmstadt/einander-helfen/files/5971095/Strolche_post.txt)

**Comment by xcaverxiii** [comment]
This will be fixed with #333.

**Comment by DianaPankratz** [comment]
This problem is still not fixed in #333. See search of "Internationale Strolche" in "Köln".

**Comment by DianaPankratz** [comment]
This issue is fixed in the list but not in the details view. E.g. search "Internationale Strolche" in "Köln". You will receive this result:
![image](https://user-images.githubusercontent.com/73997936/119709775-df265780-be5d-11eb-90c2-295cfd22923c.png)
