### ISSUE TITLE
Some Crawler misrepresents special characters

### ISSUE THREAD

**Issue by jonas-hda** [hochschule-darmstadt/einander-helfen#288]
**Describe the bug**
The ein-jahr-freiwillig crawler misrepresents certain special characters like `&` and replaces them with `&amp;` when scraping the page.

**To Reproduce**
Reproducing this error might be tricky as it is based on the crawled data and the post might no longer exist on the original site.
Steps to reproduce the behaviour:
1. Go to 'resultpage'
2. Search for 'PhorMinis'
3. Click on post

Alternatively:
Use the attached sourcecode of the original post to crawl the post even if its no longer on the website, use the debugger to look at the posts data, the `&` are replaced with `&amp;`.

**Expected behavior**
The post data should not replace `&` with `&amp;`.

**Solution**
[`html.unescape(s)`](https://docs.python.org/3/library/html.html#html.unescape) can be used to unescape htmp strings.

**Screenshots**
Search result:
![postresult](https://user-images.githubusercontent.com/74006324/107758508-46911f00-6d27-11eb-945b-eea81d00011d.PNG)

Detail page of 1 post:
![posting](https://user-images.githubusercontent.com/74006324/107758567-5d377600-6d27-11eb-8eb3-6534d54141e5.png)

Original post:
![originalSite](https://user-images.githubusercontent.com/74006324/107758609-6b859200-6d27-11eb-84e8-252ae4db4f08.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 88.0.4324.104

 - OS: Windows 10
 - Browser Firefox
 - Version 85.0.2 (64-Bit)

**Additional context**
Sourcecode of site:
[sourcecode.txt](https://github.com/hochschule-darmstadt/einander-helfen/files/5971541/sourcecode.txt)

This Issue is part of the original issue #283

**Comment by jonas-hda** [comment]
To investigate this issue, compare the data extraction of the ein-jahr-freiwillig crawler with the EhrenamtHessenScraper and GuteTatBerlinScraper. While no posts that also show this bug have been found for the BundesFreiwilligendienst-Scraper and WeltwaertsScraper could be found, its highly likely that they show the same behaviour when presented with the same post to crawl.

**Comment by KaiDrieHda** [comment]
Fixed by #287
