### ISSUE TITLE
Split ResultPage.vue into smaller components

### ISSUE THREAD

**Issue by theErikss0n** [hochschule-darmstadt/einander-helfen#291]
**Reason (Why?)**
Currently the ResultPage component is quite large which negatively affects maintainability

**Solution (What?)**
As ResultPage is a view, we should extract ui-components out of the view.

**Relation to other Issues**
#286 

**Acceptance criteria**
* ResultPage itself should contain little to no logic
* ResultPage should be significantly smaller
* The extracted components should be small

**Comment by xcaverxiii** [comment]
this should include this issue #125
