### ISSUE TITLE
Split Home.vue into smaller components

### ISSUE THREAD

**Issue by theErikss0n** [hochschule-darmstadt/einander-helfen#292]
**Reason (Why?)**
Home.vue could be smaller.

**Solution (What?)**
Extract  ui-components out of Home

**Relation to other Issues**
#286

**Acceptance criteria**
* Home.vue is smaller
* No ui-components that could be extracted remain

**Comment by xcaverxiii** [comment]
Maybe is done in #298

**Comment by xcaverxiii** [comment]
@theErikss0n a lot of Home.vue refactoring are done by #298. Only the Cards could be also extracted as a new component. Do you think this is necessary? If not please close this issue.

**Comment by theErikss0n** [comment]
It is not important, but the cards are it's own thing, can be easily extracted and helps so that each component should d only one thing.
