### ISSUE TITLE
Combine store files

### ISSUE THREAD

**Issue by xcaverxiii** [hochschule-darmstadt/einander-helfen#299]
**Problem**
Currently there are multiple storage modules. Each module is implemented by different files, separated by the store functionality. This makes it hard to read and get an overview of one whole module. 

**Solution**
Merge the different files from a store module into one file. 
Also the modules themselves does not have clearly separated context from each other. It could be possible to merge them into one store.

**Relation to other Issues**
#286

**Comment by xcaverxiii** [comment]
Some improvements on this are done by working on this issue #291. See upccoming pullrequest.

**Comment by DianaPankratz** [comment]
#333 is now merged. Is this issue still necessary?

**Comment by xcaverxiii** [comment]
> #333 is now merged. Is this issue still necessary?

yes
