### ISSUE TITLE
Make the hamburger button bigger in mobile view

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#320]
**Reason (Why?)**
The current hamburger button looks out of proportion. The UI should be as uniform as possible. 

**Solution (What?)**
Enlarge the hamburger button, until it's roughly the size of the search button.

**Out of scope**
The web and tablet view.

**Comment by xcaverxiii** [comment]
@KaiDrieHda Is this still necessary? How much bigger?  *1.5?  *1.2?

**Comment by DianaPankratz** [comment]
I am not sure. I tried 1.2, 1.3 and 1.5:

![image](https://user-images.githubusercontent.com/73997936/119845506-9deb8180-bf09-11eb-9e6c-0a1fc90a9111.png)
![image](https://user-images.githubusercontent.com/73997936/119845759-d5f2c480-bf09-11eb-8297-095162b816a3.png)
![image](https://user-images.githubusercontent.com/73997936/119845460-8f9d6580-bf09-11eb-9fe5-a9257380de0d.png)

I think 1.5 is the best. What do you think @KaiDrieHda

**Comment by xcaverxiii** [comment]
@DianaPankratz please see changes in #376

**Comment by DianaPankratz** [comment]
At the moment the size of the icon is not consistent: The button is still small on Home.
