### ISSUE TITLE
Choose better picture cutouts on mobile view

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#323]
**Reason (Why?)**
We want the UI as aesthetically pleasing to the user as possible.

**Solution (What?)**
Look at the way the pictures on home and result page are cutout on mobile view, then improve accordingly. The user should be able to see the main people/situation depicted.

**Out of scope**
Web view. Anything that is not the pictures on home and result page.

**Comment by theErikss0n** [comment]
closed by #454
