### ISSUE TITLE
The website itself should be non-scrollable in web view

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#324]
**Reason (Why?)**
The user could be confused by being able to scroll the list of results as well as the website itself.

**Solution (What?)**
Make the home and result page fit on the screen completely and eliminate the scrolling. Pay attention to responsiveness and make sure the pages fit into any screen size completely. This only applies to web view. 

**Out of scope**
Mobile view. "About", "imprint" and "privacy" pages.

**Comment by xcaverxiii** [comment]
This getting fixed with in this issue #291. See upcomming pullrequest.

**Comment by DianaPankratz** [comment]
Done with #333
