### ISSUE TITLE
All text on the map should be in latin letters 

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#325]
**Reason (Why?)**
Most users are not able to read the names of locations if they're not written in latin letters.

**Solution (What?)**
Find out if there is a version of OpenStreetMap that shows all the text in latin characters and embed it.

**Out of scope**
Anything that is not the map.

**Comment by xcaverxiii** [comment]
Do you have a screenshot of what do you exactly mean?

**Comment by KaiDrieHda** [comment]
![image](https://user-images.githubusercontent.com/73997608/118147050-7c6d9e80-b40f-11eb-9bc2-3bcb943fb82c.png)
E.g. these should be in latin letters, so they can be read by all users.
