### ISSUE TITLE
Text changes of the home page header

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#331]
**Reason (Why?)**
The information in the header should be concise and advertise the website.

**Solution (What?)**
Change the main text in the header from:

> Das schnelle Suchportal für Freiwilligenarbeit

To:

> Das Portal für Freiwilligenarbeit

Below that, add a subtitle of how many job offers there are on the website at that moment:

> Aktuell xxxx nationale und xxxx internationale Stellenangebote zur Auswahl

xxxx should be the respective number of job offers in the national/international section. Also add into that subtitle the icons for national and international (i.e. the germany flag and the globe). The numbers should be updated with each crawling of data.

**Out of scope**
The result page or any page that is not the home page. Mobile view.

**Comment by xcaverxiii** [comment]
Do you know, how the query for this data should look like?

**Comment by DanielKraft** [comment]
> 
> 
> Do you know, how the query for this data should look like?

The following two queries should return the number of national and international posts.

##  Number of national posts
```json
{
    "track_total_hits": true,
    "query": {
        "bool": {
            "must_not": {
                "term": {
                    "categories": "international"
                }
            }
        }
    }
```

##  Number of international posts
```json
{
    "track_total_hits": true,
    "query": {
        "bool": {
            "must": {
                "term": {
                    "categories": "international"
                }
            }
        }
    }
}
```

## Example response
Only the number of posts is returned via the following path: `/api/_search/posts/?filter_path=hits.total`
```json
{
    "hits": {
        "total": {
            "value": 22306,
            "relation": "eq"
        }
    }
}
```

**Comment by xcaverxiii** [comment]
@KaiDrieHda ist this like expected?

![image](https://user-images.githubusercontent.com/25961416/119126810-d126a000-ba33-11eb-9d9f-8b16bbf6cb18.png)
![image](https://user-images.githubusercontent.com/25961416/119126943-fa473080-ba33-11eb-8a68-5730dc2034d3.png)

Is currently just dummy data.

**Comment by DianaPankratz** [comment]
When the window is smaller and the text is splitted into two lines, it looks weird because all lines have the same width.
Could you try something like that? The asymmetry looks much better.
Please make sure that "xxx (flag) nationale" and "xxx (flag) internationale" should allways be together without a linebreak. The linebreak should be after "und" or after "nationale".

![image](https://user-images.githubusercontent.com/73997936/119138755-84969100-ba42-11eb-8957-3d17a3b9aa25.png)

**Comment by xcaverxiii** [comment]
@KaiDrieHda 
Is this ok?

![image](https://user-images.githubusercontent.com/25961416/119335296-7c319680-bc8c-11eb-8075-a7d9a4669824.png)

**Comment by DianaPankratz** [comment]
> @KaiDrieHda
> Is this ok?
> 
> ![image](https://user-images.githubusercontent.com/25961416/119335296-7c319680-bc8c-11eb-8075-a7d9a4669824.png)

Perfect!
