### ISSUE TITLE
Exchange one of the carousel pictures on home page

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#332]
**Reason (Why?)**
The picture of the crying child might give off a negative energy.

**Solution (What?)**
Exchange the second picture in the carousel (the crying child, holding their hands in front of their face) with a more positive picture of a child. 

**Out of scope**
Anything on the page other than that one picture of the crying child.

**Comment by xcaverxiii** [comment]
Is there already a picture with which the bad picture should be replaced?
