### ISSUE TITLE
Add a new page for linking to additional volunteer work providers

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#337]
**Reason (Why?)**
Linking to other providers gives the user even more possibilities to engage in volunteer work. Also, provided that the other websites also link to us, this will increase our ranking for being found by search engines.

**Solution (What?)**
Add a new page called "Weiterführende Links", that can be reached through the menu and the footer. On that page there should be links to as many volunteer work providers as possible in alphabetical order.

![image](https://user-images.githubusercontent.com/73997608/122095019-1f4d7a00-ce0d-11eb-8574-45d2de6cb7a3.png)

 
**Out of scope**
Any of the existing pages except for the menu component for adding the link to the new page.

**Comment by xcaverxiii** [comment]
Is there already an layout design for this page? And is there a list of pages to link to yet?

**Comment by KaiDrieHda** [comment]
Regarding layout for this page my opinion is the following: 
General layout should be like the "About"-page. The headline and the links to this page via the menu and the footer should say "Weitere Anbieter". Below that a short explanatory test like: "Hier finden Sie weitere Anbieter ehrenamtlicher Tätigkeiten." 
Then follow the links to the other providers, sorted alphabetically with the first letter as headlines, separating the links to be more easily readable (see attached screenshot).
![image](https://user-images.githubusercontent.com/73997608/118144548-de78d480-b40c-11eb-8f40-115814306b4e.png)
@DianaPankratz what do you think?
 
Regarding a list of pages: I am going to do some research and make up a list of the most popular volunteer work providers and then attach it to this issue.

**Comment by DianaPankratz** [comment]
I really like this idea! We can implement it like that

**Comment by KaiDrieHda** [comment]
You can find the list with the pages to link to here: 
https://docs.google.com/spreadsheets/d/19z5Z124ugiAjli4TmF-Mgl4wzxKFmTI-zFps4sb3fNM/edit?usp=sharing
