### ISSUE TITLE
Expand the wiki of "System Architecture - Frontend"

### ISSUE THREAD

**Issue by DianaPankratz** [hochschule-darmstadt/einander-helfen#349]
**Reason (Why?)**
Refactoring the frontend code resulted in new components that should be documented.

**Solution (What?)**
Expand the wiki page [System Architecture - Frontend](https://github.com/hochschule-darmstadt/einander-helfen/wiki/System-Architecture---Frontend)

**Out of scope**
Any code implementations or other wiki pages.

**Relation to other Issues**
#291 

**Acceptance criteria**
Every component should be described.

**Comment by xcaverxiii** [comment]
I updated the wiki.   
@KaiDrieHda please make an quality check.  
@theErikss0n please check if i forgot something.

**Comment by KaiDrieHda** [comment]
Did a quality check, fixed several small typos and made sure the "result page" is consistently named "posts/posts page". 
Looks really good to me, great work!
