### ISSUE TITLE
Logo in home page header stuck to left side in web view

### ISSUE THREAD

**Issue by KaiDrieHda** [hochschule-darmstadt/einander-helfen#359]
**Describe the bug**
The 'einander-helfen'-logo in the header on the home page is stuck to the left side with no margin in web view.

**To Reproduce**
1. Go to home page
2. See logo in header
(3. Compare to master version)

**Expected behavior**
There should be a margin between the left screen border and the logo.

**Screenshots**
![image](https://user-images.githubusercontent.com/73997608/119155342-5d948b00-ba53-11eb-9ecc-d0ac9194ba24.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Comment by xcaverxiii** [comment]
@KaiDrieHda this is already solved in the branch of #331

**Comment by DianaPankratz** [comment]
> @KaiDrieHda this is already solved in the branch of #331

Perfect. Then I will close this issue.
