### ISSUE TITLE
Implement coding conventions

### ISSUE THREAD

**Issue by DianaPankratz** [hochschule-darmstadt/einander-helfen#367]
**Reason (Why?)**
After the refactoring of the frontend code and the introduction of our coding conventions they should be implemented into the code. As the refactoring already reduced the complexity of the code the only implementations needed are the following:

- add comments to methods/components etc.
- refactor variable/method names
- fix linter errors and warnings

CSS refactorings to match the coding conventions are done in #297.

**Out of scope**
Backend code

**Relation to other Issues**
#286, #312, #297

**Comment by xcaverxiii** [comment]
@DianaPankratz Is the coding conventions definition phase finished?
