### ISSUE TITLE
Update source integration in the detailed view

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#41]
**Reason (Why?)**
In the detailed view the user shall be able to know the source of the post.

**Solution (What?)**
The data model of a post contains the link to a post and the source. In the detailed view the source from the model should be displayed and useable as a link. If the user clicks on the link he should be redirected to the link which is stored in the data model.

Currently the model in the backend (post.ts) does not contain the data object source. This needs to be added.

**Not doing**
The values of the link and source are given by the ETL.

**Relation to other Issues**
None

**Acceptance criteria**
The detailed view of a post contains the source. If you click it you should be redirected to the link.

**Comment by BernhardHumm** [comment]
The data model contains the following fields:

* source: string [[ e.g., www.ehrenamtssuche-hessen.de ]] : shall be displayed as Quelle

* link: URL  [[linked of crawled website]] : shall be used as href

 

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 18. Juni 2020 20:35
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Update source integration in the detailed view (#41)

 

Reason (Why?)
In the detailed view the user shall be able to know the source of the post.

Solution (What?)
The data model of a post contains the link to a post and the source. In the detailed view the source from the model should be displayed and useable as a link. If the user clicks on the link he should be redirected to the link which is stored in the data model.

Currently the model in the backend (post.ts) does not contain the data object source. This needs to be added.

Not doing
The values of the link and source are given by the ETL.

Relation to other Issues
None

Acceptance criteria
The detailed view of a post contains the source. If you click it you should be redirected to the link.
