### ISSUE TITLE
Extend the search radius if no search results are found

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#43]
**Reason (Why?)**
If the user enters a search value, the total amount of search results should be displayed so the user knows how many results exist.

**Solution (What?)**
A field that displays the total amount of the search results for the selected search. If no search result is provided for the specified radius, it is automatically expanded.  A text is to be displayed which informs the user that no results were found for his/her search settings but results were found in the radius of x.
If there is still no result another text should displayed that says for example “Es wurden keine Suchergebnisse zu Ihrer Suchanfrage gefunden.”.
If the user clicks on a page which is not already loaded, the selected page should be loaded and the loaded results should be additionally displayed on the map. The pagination should contain as many pages as it needs to display all possible posts. 

**Not doing**
/

**Relation to other Issues**
None

**Acceptance criteria**
The right amount of search results should be displayed. If the radius is increased, the correct text is displayed. The pagination contains as many pages as it needs to display all possible posts. After selecting a page which is not already loaded, the results will be loaded and displayed on the selected page and the pins are added on the map.

**Comment by jschurse** [comment]
@see https://github.com/hochschule-darmstadt/einander-helfen/pull/73

**Comment by jschurse** [comment]
Has been implemented and merged

**Comment by FiedlerJan** [comment]
> A field that displays the total amount of the search results for the selected search.

@jschurse This is not implemented.

**Comment by jschurse** [comment]
> @jschurse This is not implemented.

Gets fixed by #91

**Comment by FiedlerJan** [comment]
> Gets fixed by #91

#91 Does not implement the new field. The field can look something like that:
![Bildschirmfoto_2020-06-26_15-21-35](https://user-images.githubusercontent.com/64203299/85861934-59b7a480-b7c1-11ea-8d27-7e16e1dbcb10.png)

In this example I placed the counter in the lower left corner.

**Comment by jschurse** [comment]
What do you think about it under the pagination?
![grafik](https://user-images.githubusercontent.com/12964877/85863547-984e5e80-b7c3-11ea-8671-0300e0105d9f.png)

**Comment by FiedlerJan** [comment]
> What do you think about it under the pagination?

Looks also good.

**Comment by jschurse** [comment]
Has been deployed to staging.

**Comment by MaiThiD** [comment]
"If no search result is provided for the specified radius, it is automatically expanded. A text is to be displayed which informs the user that no results were found for his/her search settings but results were found in the radius of x.
If there is still no result another text should displayed that says for example “Es wurden keine Suchergebnisse zu Ihrer Suchanfrage gefunden.”." . is still not implemented

**Comment by jschurse** [comment]
What do you think of this?
![grafik](https://user-images.githubusercontent.com/12964877/85931663-5fe37900-b8c6-11ea-8189-12421b145cd9.png)

How shall the user be notified that the radius has been changed?
Is there a draft for this?

I would propose to use admiral snackbar (https://vuetifyjs.com/en/components/snackbars/) in this case:
![grafik](https://user-images.githubusercontent.com/12964877/85932022-e8631900-b8c8-11ea-92d3-cc5b1632b206.png)

The implementation can be tested at https://github.com/hochschule-darmstadt/einander-helfen/pull/107

**Comment by jschurse** [comment]
If the radius gets removed because no results were found this message is being displayed:
![image](https://user-images.githubusercontent.com/12964877/85933739-02a5f280-b8db-11ea-8a53-2e0568584ea0.png)

**Comment by jschurse** [comment]
The message has been reworded to 
![image](https://user-images.githubusercontent.com/12964877/85945464-2f3f2600-b93e-11ea-9bd2-b0987f581757.png)

**Comment by jschurse** [comment]
> "If no search result is provided for the specified radius, it is automatically expanded. A text is to be displayed which informs the user that no results were found for his/her search settings but results were found in the radius of x.
> If there is still no result another text should displayed that says for example “Es wurden keine Suchergebnisse zu Ihrer Suchanfrage gefunden.”." - is still not implemented

fixed by #107 
I hope this time for good :sweat_smile:

**Comment by FiedlerJan** [comment]
Solving this issue should not change the user's input. Also, the indication that the radius has been increased should be displayed in the left column.

**Comment by jschurse** [comment]
![grafik](https://user-images.githubusercontent.com/12964877/86349154-fc0fd600-bc60-11ea-9ca2-48833eba753b.png)

What do you think of this?

**Comment by FiedlerJan** [comment]
> ![grafik](https://user-images.githubusercontent.com/12964877/86349154-fc0fd600-bc60-11ea-9ca2-48833eba753b.png)
> 
> What do you think of this?

"Wir haben daher den Radius vergrößter..."
The distance to which the radius has been enlarged should be displayed. F.e. in this case 50km.

**Comment by jschurse** [comment]
What do we display, if the radius has been extended to 'überall'?

**Comment by jschurse** [comment]
`Wir haben daher den Radius auf 25 km erhöht`
`Wir haben daher den Radius auf Überall erhöht`?

**Comment by FiedlerJan** [comment]
> What do we display, if the radius has been extended to 'überall'?

"Wir haben den Radius auf 50km erweitert."
"Wir den Radius in aus der Suche genommen, da keine Suchergebnisse innerhalb von 50km vorliegen."

How about this?

**Comment by FiedlerJan** [comment]
> Wir haben daher den Radius auf 25 km erhöht

Sounds better than

> "Wir haben den Radius auf 50km erweitert."

**Comment by BernhardHumm** [comment]
Suggestion:

 

„Folgende Ergebnisse werden in einem Umkreis von mehr als 50 km gefunden.“

 

 

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 2. Juli 2020 13:18
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Extend the search radius if no search results are found (#43)

 

What do we display, if the radius has been extended to 'überall'?

"Wir haben den Radius auf 50km erweitert."
"Wir den Radius in aus der Suche genommen, da keine Suchergebnisse innerhalb von 50km vorliegen."

How about this?

**Comment by jschurse** [comment]
![grafik](https://user-images.githubusercontent.com/12964877/86395586-c5f24680-bca0-11ea-9dda-c48869752300.png)


I changed the messages and emphasised the location and distance in the post

**Comment by jschurse** [comment]
Fixed again by #134
