### ISSUE TITLE
Market analysis for a suitable web service

### ISSUE THREAD

**Issue by SeverinNovack** [hochschule-darmstadt/einander-helfen#431]
Reason (Why?)
The separation from the h_da servers will be necessary sooner or later, since the project will be continued afterwards as a standalone project and not with the h_da.

Solution (What?)
Gather requirements for the web service to be selected.
Conduct a market analysis and weigh up which web service offers the best value for money.

**Comment by tpachmann** [comment]
**System Requirements:**
- Assuming we need a minimum of 8/16 GB RAM, 2 CPU cores per node/server
- We need 2 environments (staging / production)

**Comment by tpachmann** [comment]
## Price Comparison: AWS
Pricing Calculator (4 different scenarios):
https://calculator.aws/#/estimate?id=2c6ac21447beee68de5006c9b977876df4c5ee78

| Server Configuration   | Short Term Reservation (1 Year) | Long Term Reservation (3 Years) |
|------------------------|---------------------------------|---------------------------------|
| EC2 (2x 2 vCores, 8 GB RAM) | 77,80 USD per month             | 55,61 USD per month             |
| EC2 (2x 2 vCores, 16 GB RAM) | 118,98 USD per month            | 83,79 USD per month             |

**Comment by tpachmann** [comment]
## Price Comparison: MS Azure
Pricing Calculator (4 different scenarios):
https://azure.com/e/5224f738a6af4ef28651c2d4807fddbf

| Server Configuration   | Short Term Reservation (1 Year) | Long Term Reservation (3 Years) |
|------------------------|---------------------------------|---------------------------------|
| 2x D2ads v5 (2 vCores, 8 GB RAM) | 107,71 USD per month             | 69,39 USD per month             |
| 2x D2d v4 (2 vCores, 16 GB RAM) | 117,22 USD per month            | 75,49 USD per month             |

**Comment by tpachmann** [comment]
## Price Comparison: Hetzner

| Server Configuration   | On-Demand |
|------------------------|---------------------------------|
| 2x CX31 (2 vCores, 8 GB RAM) | 21,81 EUR per month |
| 2x CX41 v4 (4 vCores, 16 GB RAM) | 37,84 EUR per month |

**Comment by SeverinNovack** [comment]
## Price Comparison: Google Cloud Computing
Pricing Calculator (4 different scenarios):
https://cloud.google.com/products/calculator

| Server Configuration   | Short Term Reservation (1 Year) | Long Term Reservation (3 Years) |
|------------------------|---------------------------------|---------------------------------|
| 2x e2-standard-2 (2 vCores, 8 GB RAM, 30GB disk size) | 82,29 USD per month             | 59,60 USD per month             |
| 2x e2-highmen.2 (2 vCores, 16 GB RAM) | 110,00 USD per month            | 79,40 USD per month             |

**Comment by SeverinNovack** [comment]
## Price Comparison: DigitalOcean

https://cloud.digitalocean.com/droplets/new

| Server Configuration   | On-Demand |
|------------------------|---------------------------------|
| 1x Basic - Regular Intel (4 CPUs, 8 GB RAM) | 40,00 USD per month |
| 1x Memory Optimized (2 CPUs, 16 GB RAM) | 80,00 USD per month |

**Comment by tpachmann** [comment]
**Further TODOs:**
- [ ] Long term monitoring on how much resources we really need (w/ ETL pipeline running)

**Comment by mhendlich** [comment]
Just some thoughts:

I havent checked the exact resource usage of the scraping script but it seems mostly I/O-bottlenecked.
A system with 1-2 vCores and even just 1-2GB RAM might already be enough.

Also I assume that for our project its important that hosting is as simple as possible, mostly since the maintainers change every semester. AWS/Azure/GCloud are mighty tools but can be very confusing for non-experts. 
I assume the simplest way to host our application would be to containerize it and use any simple service that just runs a container for you. We use Heroku in exactly this way at work, which works very well. [DO](https://docs.digitalocean.com/products/app-platform/how-to/deploy-from-registry/) bight be an even better deal, as far as I remember their app service just bills you for the underlying droplet you use (which are quite cheap).

**Comment by SeverinNovack** [comment]
Document can be found under: [http://141.100.60.99:81/index.php/apps/files/?dir=/EinanderHelfen/Reviews&fileid=7336](http://141.100.60.99:81/index.php/apps/files/?dir=/EinanderHelfen/Reviews&fileid=7336)
