### ISSUE TITLE
Add vscode devcontainers for FE & BE environments

### ISSUE THREAD

**Issue by mhendlich** [hochschule-darmstadt/einander-helfen#433]
**Reason (Why?)**
There are various issues with inconsistencies when running the frontend application or fetching its dependencies. These stem from two main problems:

1. There is no defined version of node that shall be used (this could be solved via an entry in the `engines` field of the `package.json`
2. No lockfile checked in
3. Different OSes used when developing

While the first two factors could be solved directly, even their solutions do not fully guarantee a consistent development environment for all developers.

**Solution (What?)**
As VS code was already chosen as the main development editor for this project, we can make use of its [Devcontainer feature](https://code.visualstudio.com/docs/remote/containers).

The overall concept behind this feature is best explained in this diagram:
![architecture-containers](https://user-images.githubusercontent.com/14072571/139857529-cad12913-b37d-43e9-8f7e-5c9bf3defc9d.png)

**Out of scope**
Devcontainer settings should not change any editor settings that are considered personal preference as themes and keybindings.

**Acceptance criteria**
The devcontainer environment should include all software and configurations which are needed for a consistent development experience. For the FE these are:

1. VSCode plugins which run inside the container (prettier, vetur, eslint, ...?)
2. VSCode settings
3. Node environment

Developing inside this container should be fast enough to not be annoying. 
This might be an issue on windows hosts using the WSL2 engine for Docker Desktop, as this runs a VM for the docker environment. As the VSCode server mounts the local file system inside this VM, file system performance is highly degraded - especially when running on a HDD. This will be noticeable when doing package installs, resulting in a slightly longer time needed. As this does not happen often, this tradeoff is considered acceptable.
Normal development tasks like running the dev server, building the application or running tests would not be noticeably slower as most time is spent transpiling sources.

**Next steps**
The environment in which the application is build for staging/production should be equal to the development environment.

**Comment by theErikss0n** [comment]
We should also document the usage of the dev containers in our wiki.
