### ISSUE TITLE
Landing Page image carousel refactoring

### ISSUE THREAD

**Issue by Alltagsheld** [hochschule-darmstadt/einander-helfen#434]
**Reason (Why?)**
Dragging an image inside the carousel on the landing page leads to misbehaviour of the wrapping carousel component.
This can be seen by the 'ghostimage' at your cursor and the carousel's dragging not being able to work until the user released the mouse.

**Solution (What?)**
the images dragging ability has been removed. Now, the carousel can be used as expected.

**Acceptance criteria**
The carousel should be working as expected, providing a smoothe slide, without breaking the dragging functionality by being able to drag single images inside the carousel

**Comment by oneamanish** [comment]
see my pull req.
