### ISSUE TITLE
Rename title

### ISSUE THREAD

**Issue by ArnoldPoradaStud** [hochschule-darmstadt/einander-helfen#444]
**Reason (Why?)**
It cannot be seen at first glance what the site offers

**Solution (What?)**
The title should be changed from “Das Portal für Freiwilligenarbeit” to “Meine 
Freiwilligenarbeit finden”

**Out of scope**
Anything that is out of scope and shall not be implemented

**Relation to other Issues**
Provide additional context (link relevant issues)

**Acceptance criteria**
Describe acceptance criteria for testing (Don't repeat reason and solution again)

**Comment by theErikss0n** [comment]
As discussed in the PR, we don't want to to this change.
