### ISSUE TITLE
Optimizing radius search

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#45]
**Reason (Why?)**
The user should be able to limit or expand the displayed search results with the location and radius.

**Solution (What?)**
The radius search must be optimized. The search results are filtered by the selected location and radius. If the radius is changed, the result list is updated with the corresponding contributions.

**Not doing**

**Relation to other Issues**
#24 

**Acceptance criteria**
The right search results should be displayed on the result page based on the selected radius.

**Comment by jschurse** [comment]
Has been implemented and merged
