### ISSUE TITLE
Check built output

### ISSUE THREAD

**Issue by theErikss0n** [hochschule-darmstadt/einander-helfen#467]
**Reason (Why?)**
Google Lighthouse claims that our text (js / css) is not served with compression (like gzip) and that we serve unused javascipt.

**Solution (What?)**
Check and fix text compression. This probably needs some work with the vue build command and webpack.

**Comment by mhendlich** [comment]
`Google Lighthouse claims that our text (js / css) is not served with compression (like gzip)`

This can be fixed in nginx by enabling zip (and brotli if possible) compression. Precompressing ressources is ususally not necessary

**Comment by mhendlich** [comment]
This will be fixed in #483
