### ISSUE TITLE
Specify and automate the SEO benchmarks

### ISSUE THREAD

**Issue by Granoffel** [hochschule-darmstadt/einander-helfen#482]
**Reason (Why?)**
We need a measurement for the SEO enchantments to make sure the taken measures have the right effect on the ranking.

**Solution (What?)**
Create a list with keywords we want to target. Build an script ore use a Tool to check your Ranking on the Keywords every day.

**Keywords**
- fsj
- föj
- volunteering
- freiwilliges ökologisches Jahr
- Ehrenamt
- ehrenamtliche Tätigkeit
- fsj stellen
- Freiwilligenarbeit
- ehrenamtliche Arbeit
- Auslandsjahr
- Freiwilligendienst
- gap year
- soziales engagement
- Seniorenbetreuung
- Jugendarbeit

**Comment by BernhardHumm** [comment]
Ideally the benchmark ranking results in on number which can be compared 
before and after each release.

Please add the search terms for the benchmark (as decided on 17/11/2021) to 
the Github issue.

**Comment by Granoffel** [comment]
As presented in the meeting on November 24th, 2021, https://www.seobility.net/de/ is used for the benchmark. The keywords specified above were stored here and daily checked.
