### ISSUE TITLE
Optimization of the map loading time

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#49]
**Describe the bug**
Sometimes it takes more than ten seconds to load the amp on the results page.

**To Reproduce**
1. Go to the result page
2. See error

If this does not reproduces the error follow these steps:
1. Go to the result page
2. Hover with your mouse over the map
3. Scroll down with your mouse

**Expected behavior**
The map should be loaded in a resonable time (1 sec).

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64203299/85152255-11463700-b255-11ea-9f51-f74582bdd83f.png)

**Desktop (please complete the following information):**
 - Windows 10
 -  Firefox
 -  Version 77

**Smartphone (please complete the following information):**
Not used for testing.

**Additional context**
Is it possible to store the map in the cache?

**Comment by jschurse** [comment]
It seems to me caused by the openstreetmap loading times. This is realy strange since the tiles are loading very fast on https://www.openstreetmap.org

![grafik](https://user-images.githubusercontent.com/12964877/85224192-d2d18900-b3c8-11ea-848a-98c1542e2b3f.png)

**Comment by jschurse** [comment]
@FiedlerJan is this still an issue? Hadn't had this problem the last days.

**Comment by andresesam** [comment]
Is the map cached in any way?

**Comment by FiedlerJan** [comment]
> @FiedlerJan is this still an issue? Hadn't had this problem after the last merges.

Yes, it still exists. Sometimes it's faster and sometimes slower.

**Comment by jschurse** [comment]
Hey @FiedlerJan,
I had a look into this: https://github.com/hochschule-darmstadt/einander-helfen/pull/110
I changed the v-if on the map to a v-show so the element gets rendered always and is just hidden by css display:none. (With v-if the element gets completely destroyed when the detail of a post is shown)
This has the effect that map layers can be reused and don't need to be recreated on each switch from detail to map.

I also added an explicit rerender method which is called when the component is mounted and each time the map is being opened again.
Could you please tell me if this fixed the loading bug on your machine too?

**Comment by jschurse** [comment]
After reloading the page some time the bug still persists...

**Comment by FiedlerJan** [comment]
The loading times improved without further investigation.

![grafik](https://user-images.githubusercontent.com/64203299/105333145-acc9cc80-5bd5-11eb-9298-387b6ba90c67.png)

Can some else verify this?

**Comment by jonas-hda** [comment]
Tested this over the course of 2 days at different times and could not reproduce the bug. Occasionally loading times would spike but always stayed below 80ms, issue is therefore closed.
