### ISSUE TITLE
Location suggestion does not work properly on smartphones

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#51]
**Describe the bug**
Location suggestion does not work properly on mobile.

**To Reproduce**
1. Go to 'home' via smartphone
2. Click on 'the location textfield'
3. Type a zipcode like ‘63110’ or a location like ‘Frankfurt’

**Expected behavior**
Matching locations should be suggested for the incompleted as well as for the completed input.

**Screenshots**
![location_bug_on_mobile](https://user-images.githubusercontent.com/64202398/85154243-83b81680-b257-11ea-833e-2db21ed90c64.jpeg)

**Desktop (please complete the following information):**
/

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Browser Google Chrome
 - Version 83.0.4103.106

**Additional context**
/

**Comment by andresesam** [comment]
I can neither understand nor reproduce the problem. The logic of the application is not changed by the size of the terminal device. Maybe you were briefly disconnected from the Internet ? Can you test the whole thing again? Everything works for me (and I would also be very surprised if it doesn't work)

**Comment by MaiThiD** [comment]
> I can neither understand nor reproduce the problem. The logic of the application is not changed by the size of the terminal device. Maybe you were briefly disconnected from the Internet ? Can you test the whole thing again? Everything works for me (and I would also be very surprised if it doesn't work)

@FiedlerJan also verified this behaviour in his test

**Comment by FiedlerJan** [comment]
I used the following smartphone:

- Device: OnePlus 6T
- OS: Android 10
- Browser: FireFox
- Version 68.9.0

And I have the same problem.

**Comment by jschurse** [comment]
Also have the same issue

- Android 9
- Firefox 68.9.0

**Comment by FiedlerJan** [comment]
The search bar uses the key up event: https://github.com/hochschule-darmstadt/einander-helfen/blob/staging/app/src/components/ui/LocationSearchBar.vue#L91

This event is not available on all smartphones.

**Comment by andresesam** [comment]
Hi, can someone test for me if the keypress event will may work on your phones? 
I changed the event but recognized that I don`t have an Android phone, where i can verify the scenario 😨 

https://github.com/hochschule-darmstadt/einander-helfen/tree/bug/51/smartphone_suggestion

**Comment by MaiThiD** [comment]
> Hi, can someone test for me if the keypress event will may work on your phones?
> I changed the event but recognized that I don`t have an Android phone, where i can verify the scenario 😨
> 
> https://github.com/hochschule-darmstadt/einander-helfen/tree/bug/51/smartphone_suggestion
> 
> @MaiThiD @FiedlerJan

It is still not working for me

**Comment by andresesam** [comment]
> > Hi, can someone test for me if the keypress event will may work on your phones?
> > I changed the event but recognized that I don`t have an Android phone, where i can verify the scenario 😨
> > https://github.com/hochschule-darmstadt/einander-helfen/tree/bug/51/smartphone_suggestion
> > @MaiThiD @FiedlerJan
> 
> It is still not working for me

Hm pity :/ Just to make sure , you tested the local branch not the staging server?

**Comment by MaiThiD** [comment]
> > > Hi, can someone test for me if the keypress event will may work on your phones?
> > > I changed the event but recognized that I don`t have an Android phone, where i can verify the scenario 😨
> > > https://github.com/hochschule-darmstadt/einander-helfen/tree/bug/51/smartphone_suggestion
> > > @MaiThiD @FiedlerJan
> > 
> > 
> > It is still not working for me
> 
> Hm pity :/ Just to make sure , you tested the local branch not the staging server?

yes: bug/51/smartphone_suggestion

**Comment by andresesam** [comment]
I have to ask you to test it again 😄  I read in some posts that the keydown could work as an alternative. Can someone test it for me again (Because I still don't have an Android device available, as before). @jschurse forgot to mention you as well :D If this event also not working are there other suggestions=?

**Comment by FiedlerJan** [comment]
> Can someone test it for me again

Still not working on 

> * Device: OnePlus 6T
> 
> * OS: Android 10
> 
> * Browser: FireFox
> 
> * Version 68.9.0

But do not ask me why. 😄

**Comment by jschurse** [comment]
Hey, 
I just had a look at this with the debugger (https://developer.mozilla.org/de/docs/Tools/Remote_Debugging/Firefox_for_Android)
I let the event-handler protocol the event it receives:

```
keyup
[...]
code: ""
[...]
key: "Backspace"
[...]
which: 8
```

As you can see the code property for which we test in the handler isn't set. Instead the key propertry is set.

So I added additional conditions to test for this

```
const handleDesktop = evt.code.startsWith('Key') || evt.code.startsWith('Digit') || evt.code === 'Backspace';
const handleMobile = Number.isInteger(evt.key) || evt.key.match(/[a-z]/i) || evt.key === 'Backspace';

if (handleDesktop || handleMobile) {
```

This seems to work both Firefox and Chrome on Android.

I opened a PR for this here: https://github.com/hochschule-darmstadt/einander-helfen/pull/108/files

@andresesam could you please verify that this still is working on iOS?
@FiedlerJan @MaiThiD can you confirm it is working as expected?

**Comment by andresesam** [comment]
@jschurse Semms to work for IOS 👍

**Comment by FiedlerJan** [comment]
> @jschurse Semms to work for IOS 👍

Please approve the PR #108.
