### ISSUE TITLE
text structure for a better ranking

### ISSUE THREAD

**Issue by Granoffel** [hochschule-darmstadt/einander-helfen#510]
**Reason (Why?)**
In order to get a better ranking, the page must have a clear structure for text. There must be an H1 heading. Texts may not be in a div element but in an article. span may only be used for decorative elements. The texts must be in a p tag.

**Solution (What?)**
Make the span element with the content "Das Portal für Freiwilligenarbeit" to an h1 tag
![image](https://user-images.githubusercontent.com/19534286/147061681-28d7b3fe-eb52-49d6-b925-25db3bbfb4e2.png)
Put the content from Card Titel and Sub Titel in one article. Keep h2 and h3 but replace the span with an p tag
![image](https://user-images.githubusercontent.com/19534286/147062206-b45f752a-f5b6-4662-a04a-54a634512cf9.png)
![image](https://user-images.githubusercontent.com/19534286/147062268-d84b3209-9825-4abe-9446-1375dd30b3f5.png)

**Comment by theErikss0n** [comment]
As explained in #460 there should be no semantic relevant html tags in the header, but in the main content area only.

This would be an opportunity to add an explanatory header above our cards that explain what there are actually for.
Maybe something like "Was du hier finden kannst" or "Hilfe gesucht!" could help.

Thoughts or suggestions?

**Comment by theErikss0n** [comment]
This is how this could look like:
![2021-12-28_15121640701192](https://user-images.githubusercontent.com/38251684/147575603-414f8016-9bb7-4e5e-811c-7e13ecb1aa82.png)

**Comment by Granoffel** [comment]
I think the heading above the cards is a very good idea! I am not so convinced of an explanatory text under the heading.
![image](https://user-images.githubusercontent.com/19534286/148079282-89a1dd01-2f8c-42d3-8e55-bfa464bfac4b.png)
