### ISSUE TITLE
URL Typo Handling WWW Resolve

### ISSUE THREAD

**Issue by Granoffel** [hochschule-darmstadt/einander-helfen#514]
**Reason (Why?)**
In Order to get a better ranking the URL Typo Handling has to be correct. Unfortunately the server does not redirect to this [Page](https://www.einander-helfen.org/) , if someone enters the URL with a "www" at the beginning.

- www.einander-helfen.org
- https://www.einander-helfen.org/

**Solution (What?)**
Adjust the server settings for redirects.

**Comment by tpachmann** [comment]
I've adjusted the DNS records in Strato and the nginx config of the production server accordingly, so this should work now.

**Comment by Granoffel** [comment]
looks great
