### ISSUE TITLE
The first post is always marked on the map

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#52]
**Describe the bug**
The first post is always marked on the map.

**To Reproduce**
1. Go to ‘home’ 
2. Enter ‘Macher/in’ as search term
3. Select a different post than the first one
4. Change to map view by closing the detail view 

**Expected behavior**
The pin should point to the location of the selected post.

**Screenshots**
![image](https://user-images.githubusercontent.com/64202398/85158777-eb249500-b25c-11ea-8e98-4be32490dbdd.png)

![image](https://user-images.githubusercontent.com/64202398/85158803-f37cd000-b25c-11ea-9059-32ef4d1a7f54.png)

**Desktop (please complete the following information):**
- OS: Windows 10
 - Browser Google Chrome
 - Version 83.0.4103.106

**Smartphone (please complete the following information):**
Not tested

**Additional context**
/

**Comment by jschurse** [comment]
This is a direct consequence of the issue described in #54 and will therefore be resolved by #54

**Comment by jschurse** [comment]
Fixed with https://github.com/hochschule-darmstadt/einander-helfen/commit/67297695b8cdda0e3d843bd80f483a53bf084114
