### ISSUE TITLE
Sort order of results

### ISSUE THREAD

**Issue by jschurse** [hochschule-darmstadt/einander-helfen#55]
The user has multiple ways of searching for results.
He can provide:

- Input for a tag or text search
- A location for a geographic search

If we have no location data available we sort the posts alphabetically.
But if we have a location given by the user we could also sort the results according to this location:
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/search-request-body.html#geo-sorting

Shall we implement the geo-sorting?

**Comment by BernhardHumm** [comment]
Yes, I think geo sorting is a good idea.

 

 

 

------------------------------------

 

 

Von: jschurse [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Juni 2020 20:05
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Assign <assign@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Sort order of results (#55)

 

The user has multiple ways of searching for results.
He can provide:

*	Input for a tag or text search
*	A location for a geographic search

If we have no location data available we sort the posts alphabetically.
But if we have a location given by the user we could also sort the results according to this location:
https://www.elastic.co/guide/en/elasticsearch/reference/7.8/search-request-body.html#geo-sorting

Shall we implement the geo-sorting?

**Comment by jschurse** [comment]
Has been implemented and can be tested here https://cai-einander-helfen-staging.fbi.h-da.de/
