### ISSUE TITLE
Content of location search bar needs to be removed twice

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#56]
**Describe the bug**
After the user has selected a location in the location search bar and he wants to change the location, he has to remove the current location and press enter one more time before he can search for a new location.

**To Reproduce**
1. Go to 'Home'
2. Click on the location search bar
3. Enter '65929'
4. Click on the given location '65929 Frankfurt am Main'
5. Remove '65929 Frankfurt am Main' from the location search bar
6. See error (You can only selected '65929 Frankfurt am Main')
7. Press backspace
8. Everything works as normal again

**Expected behavior**
If the user clears the input of the location search bar, he should be able to search again.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64203299/85170603-ecaa8900-b26d-11ea-9d22-0a657ebfe789.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 77

**Smartphone (please complete the following information):**
Not used for testing.

**Additional context**
None

**Comment by jschurse** [comment]
fixed by #103
