### ISSUE TITLE
A tag may not be selected more than once

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#57]
**Reason (Why?)**
It shall not be possible to select a tag more than once and when the tag is created, it shall no longer be in the search bar.

**Solution (What?)**
If the user added a tag to the search he should not be able to add the same tag again. Furthermore, no tags should be displayed in the search, which are already in the search. After a tag was added the value inside of the search bar should be cleared.

**Not doing**
The search algorithm.

**Relation to other Issues**
None

**Acceptance criteria**
1. User writes 'Macher/in' in the search bar.
2. User presses enter.
3. The tag 'Macher/in' should be added to the search.
4. The value of the search bar is empty.
5. User writes 'Mach' in the search bar.
6. There shall be no proposal for 'Macher/in'.
7. User writes 'Macher/in' in the search bar.
8. User presses enter.
9. The tag 'Macherin' should only be present once in the search.

**Comment by BernhardHumm** [comment]
I am confused by this issue description.

It is correct, that an already selected search tag shall not be available in the autosuggest list for the next time.

However, the user may refine the search by adding other search tags.  So, the list of tags in the search bar is NOT cleared after executing a search operation. 

 

------------------------------------

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Juni 2020 21:21
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] A tag may not be selected more than once (#57)

 

Reason (Why?)
It shall not be possible to select a tag more than once and when the tag is created, it shall no longer be in the search bar.

Solution (What?)
If the user added a tag to the search he should not be able to add the same tag again. Furthermore, no tags should be displayed in the search, which are already in the search. After a tag was added the value inside of the search bar should be cleared.

Not doing
The search algorithm.

Relation to other Issues
None

Acceptance criteria

1.	User writes 'Macher/in' in the search bar.
2.	User presses enter.
3.	The tag 'Macher/in' should be added to the search.
4.	The value of the search bar is empty.
5.	User writes 'Mach' in the search bar.
6.	There shall be no proposal for 'Macher/in'.
7.	User writes 'Macher/in' in the search bar.
8.	User presses enter.
9.	The tag 'Macherin' should only be present once in the search.

**Comment by FiedlerJan** [comment]
@BernhardHumm 
> However, the user may refine the search by adding other search tags. So, the list of tags in the search bar is NOT cleared after executing a search operation.

Not the list of tags but the search value should be cleared.

Currently if you do free text search (f.e. 'Mach') and press enter, the tag 'Mach' is added and the value inside of the search bar is still 'Mach'.
![grafik](https://user-images.githubusercontent.com/64203299/85284982-5f934a00-b490-11ea-8608-b8eb05c5e9bb.png)

This is not best practice, as the user must now delete 'Mach' from the search bar before searching for another tag.

**Comment by BernhardHumm** [comment]
Now I understand and fully agree. A screenshot often clarifies the issue.

 

My suggestion: when no entry in the autosuggest list is chosen (full text search) then indicate this by double quotes in the tag,

In the example: “Mach”

(analogous to openArtBrowser).

 

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Montag, 22. Juni 2020 14:01
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] A tag may not be selected more than once (#57)

 

@BernhardHumm <https://github.com/BernhardHumm> 

However, the user may refine the search by adding other search tags. So, the list of tags in the search bar is NOT cleared after executing a search operation.

Not the list of tags but the search value should be cleared.

Currently if you do free text search (f.e. 'Mach') and press enter, the tag 'Mach' is added and the value inside of the search bar is still 'Mach'.
 <https://user-images.githubusercontent.com/64203299/85284982-5f934a00-b490-11ea-8608-b8eb05c5e9bb.png> 

This is not best practice, as the user must now delete 'Mach' from the search bar before searching for another tag.

**Comment by andresesam** [comment]
@BernhardHumm 
I have an alternative suggestion to your free text search idea. How about as soon as no more tags match the search a small info text like in the following screenshot is provided. I find this a bit more user-friendly than simply putting the tag in quotation marks when it's a free text search.

![1](https://user-images.githubusercontent.com/39090774/85942253-7b7f6b80-b928-11ea-8451-201c8b371c52.png)
The previous behaviour remains of course unchanged. Only as soon as the free text search no longer matches the provided tags, the info text will appear.

**Comment by FiedlerJan** [comment]
> ![1](https://user-images.githubusercontent.com/39090774/85942253-7b7f6b80-b928-11ea-8451-201c8b371c52.png)

This looks like good information for the user.

**Comment by jschurse** [comment]
>  when the tag is created, it shall no longer be in the search bar.

This has not been implemented. See #113

**Comment by jschurse** [comment]
Fixed by #113

**Comment by BernhardHumm** [comment]
Good idea!

 

 

 

------------------------------------

 

Von: andresesam [mailto:notifications@github.com] 
Gesendet: Sonntag, 28. Juni 2020 10:19
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] A tag may not be selected more than once (#57)

 

@BernhardHumm <https://github.com/BernhardHumm> 
I have an alternative suggestion to your free text search idea. How about as soon as no more tags match the search a small info text like in the following screenshot is provided. I find this a bit more user-friendly than simply putting the tag in quotation marks when it's a free text search.

 <https://user-images.githubusercontent.com/39090774/85942253-7b7f6b80-b928-11ea-8451-201c8b371c52.png> 
The previous behaviour remains of course unchanged. Only as soon as the free text search no longer matches the provided tags, the info text will appear.
