### ISSUE TITLE
Resultpage: Reduce the whitespaces between labels and values, change button name and add location to subtitle

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#58]
**Reason (Why?)**
The user should be able to read the detailed text without great effort.

**Solution (What?)**
The white spaces between the labels and values on the detail view should be reduced. Possibly implement it as a table?

The button "zum Stellenangebot" has to be changed to "zum Ehrenamt".

The location should be displayed in subtitles: e.g. :
Ausbildungspate/in  
Florstadt - gesucht werden Lebens- und berufserfahrene Florstädter Ausbildungspaten ...

**Not doing**
/

**Relation to other Issues**
/

**Acceptance criteria**
The whitespace between label and value should be reduced, especially when zooming out.
Button was renamed and the location of the post is displayed on the subtitle.

**Comment by BernhardHumm** [comment]
Button label: „Zum Angebot“

 

 

 

------------------------------------

 

 

Von: MaiThiD [mailto:notifications@github.com] 
Gesendet: Freitag, 19. Juni 2020 21:50
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Resultpage: Reduce the whitespaces between labels and values, change button name and add location to subtitle (#58)

 

Reason (Why?)
The user should be able to read the detailed text without great effort.

Solution (What?)
The white spaces between the labels and values on the detail view should be reduced. Possibly implement it as a table?

The button "zum Stellenangebot" has to be changed to "zum Ehrenamt".

The location should be displayed in subtitles: e.g. :
Ausbildungspate/in
Florstadt - gesucht werden Lebens- und berufserfahrene Florstädter Ausbildungspaten ...

Not doing
/

Relation to other Issues
/

Acceptance criteria
The whitespace between label and value should be reduced, especially when zooming out.
Button was renamed and the location of the post is displayed on the subtitle.
