### ISSUE TITLE
Header overlaps images

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#59]
**Describe the bug**
On the page Home the header overlaps the images of the carousel.

**To Reproduce**
1. Go to 'Home'
2. Open the inspector view of your browser (F12 in Firfox)
3. Use the element selection tool
4. Select the image carousel

**Expected behavior**
The image carousel should start below the header.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64203299/85175062-f71d5080-b276-11ea-90dc-45e7fc4425c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 77

**Smartphone (please complete the following information):**
Not used for testing.

**Additional context**
None

**Comment by sgrobarek** [comment]
@andresesam the header should have the same size as the searchbar in the resultpage

**Comment by FiedlerJan** [comment]
The logo should be visible in full height.
