### ISSUE TITLE
Location: Autocomplete should start after the first input

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#64]
**Reason (Why?)**
Location suggestions should not appear when the user selects the location text field. Owing to the fact that it is irrelevant to the user.

**Solution (What?)**
The autocomplete should only be started after the first input.

**Not doing**
Implementation of the location search

**Relation to other Issues**
/

**Acceptance criteria**
Location autocomplete starts after the first input.

**Comment by jschurse** [comment]
I´m not sure if the autocomplete component provides this feature.
If we provide no items at start we get an box with a hint that no data is available.
![grafik](https://user-images.githubusercontent.com/12964877/85443675-d6fcd280-b591-11ea-9e33-83a861a8f676.png)
The message is easily customizable though and could hint the user to start typing.

**Comment by BernhardHumm** [comment]
I don’t think we need an additional message here.

 

 

------------------------------------

 

 

Von: jschurse [mailto:notifications@github.com] 
Gesendet: Dienstag, 23. Juni 2020 20:42
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Location: Autocomplete should start after the first input (#64)

 

I´m not sure if the autocomplete component provides this feature.
If we provide no items at start we get an box with a hint that no data is available.
 <https://user-images.githubusercontent.com/12964877/85443675-d6fcd280-b591-11ea-9e33-83a861a8f676.png> 
The message is easily customizable though and could hint the user to start typing.

**Comment by MaiThiD** [comment]
> I´m not sure if the autocomplete component provides this feature.
> If we provide no items at start we get an box with a hint that no data is available.
> ![grafik](https://user-images.githubusercontent.com/12964877/85443675-d6fcd280-b591-11ea-9e33-83a861a8f676.png)
> The message is easily customizable though and could hint the user to start typing.




we could use hide-no-data
![image](https://user-images.githubusercontent.com/64202398/85567776-6d340580-b631-11ea-87cb-5c64c9aa36a2.png)
