### ISSUE TITLE
Homepage: Change categories titlebox from round corners to pointed corners

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#65]
**Reason (Why?)**
When looking at the four suggestions, the user should focus on the images or their text. Unfortunately, the black corners distract the user.

**Solution (What?)**
The white rectangles should not contain round corners, but pointed corners.

**Not doing**
/

**Relation to other Issues**
/

**Acceptance criteria**
The white rectangles contain pointed corners.

**Comment by jschurse** [comment]
Done in https://github.com/hochschule-darmstadt/einander-helfen/pull/74
