### ISSUE TITLE
Location search bar: Pressing 'Enter' routes to result page

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#66]
**Describe the bug**
If you select the location search bar and press ‘Enter’, you will route to the result page.

**To Reproduce**
1. Go to 'home'
2. Click on 'location search bar'
3. Press ‘Enter’

**Expected behavior**
Nothing should happen if you press ‘Enter’ in the location search bar.

**Screenshots**
It is not possible to capture this bug on screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 83.0.4103.106

**Smartphone (please complete the following information):**
Not used for testing

**Additional context**
/

**Comment by jschurse** [comment]
This will be resolved by https://github.com/hochschule-darmstadt/einander-helfen/pull/68 when it's clear when the search should be triggered

**Comment by jschurse** [comment]
Has been resolved
