### ISSUE TITLE
Web Scraping

### ISSUE THREAD

**Issue by JamieArmstrongArndt** [hochschule-darmstadt/einander-helfen#7]
**Reason (Why?)**
- Why do you want this feature? 
  - Adding this feature provides data for our application.
- What goals should be achieved? 
  - The feature should be able to get responses for a certain website and extract the desired content. 
- Is your issue related to a problem? Please describe.
  - At the moment there is no data for the frontend to display. This feature shall resolve this issue.

**Solution (What?)**
There should be a base class Crawler/Scraper, which should have overwrittable methods to add urls by using the base url and a parse function, which extracts certain content of the hmtl response. 

**Not doing**
An immediate database import

**Relation to other Issues**
\-

**Acceptance criteria**
Import multiple datasets for one website in a prescribed way

**Comment by jschurse** [comment]
@marvinseith @JamieArmstrongArndt To enable linking to a specific post we need an ID to reference to.
Currently the only ID we have is the ID generated by elasticsearch.

Will this ID will change after the next crawl?
If so we need an unique identifier for a post that won´t change on each crawl.

**Comment by marvinseith** [comment]
@jschurse taking a look into that. Could SHA the URI in the data enhancement prozess so we have a steady identifier.

**Comment by jschurse** [comment]
@marvinseith see https://github.com/hochschule-darmstadt/einander-helfen/wiki/System-Architecture
there the ID field is being described

**Comment by marvinseith** [comment]
Will close this for now, since web scraping is done for einander-helfen and can easily be extended for a new domain.
