### ISSUE TITLE
Harmonize searching behaviour 

### ISSUE THREAD

**Issue by BaderChouaib** [hochschule-darmstadt/einander-helfen#77]
**Reason (Why?)**
Currently searching posts via dropdown, searchbutton and inputted text does not harmonize well and either excludes one or the other.

**Solution (What?)**
> If this is the case then when should the URI and results be updated on the result page. On value change or when the user clicks the button?

The tags query, in the URI, should be updated on enter, the press of the search button or the selection in the drop down. The location and range should be updateded in the URI when the value is changed.

> How is this on Imprint/Privacy where the Header is also being shown?

The Header should look the same on every page except the 'Home' page. The only change to the imprint/data protection is that the query should only be redirected to the results page if the search bar was used as described at the beginning.

_Originally posted by @FiedlerJan in https://github.com/hochschule-darmstadt/einander-helfen/pull/68#issuecomment-647797225_

**Relation to other Issues**
#68 #75 
**Acceptance criteria**
The search behaviour works as proposed by @FiedlerJan on all pages

**Comment by jschurse** [comment]
fixed in https://github.com/hochschule-darmstadt/einander-helfen/pull/75/commits/f0685e338ecdefb22e9fd68e7272e21a98b1b1eb
