### ISSUE TITLE
Copyright holder of the heart-hand-shake icon should be mentioned in imprint

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#80]
**Reason (Why?)**
By using the heart-hand-shake icon we need to provide that the copyright holder is properly attributed.

**Solution (What?)**
"IIT Bombay" needs to be properly attributed in imprint with reference to the heart-hand-shake icon.

**Not doing**
/

**Relation to other Issues**
/

**Acceptance criteria**
IIT Bombay is properly attributed in imprint.

**Comment by BaderChouaib** [comment]
According to the wiki author must be mentioned on the about page (wiki > requirements):
>The logo contains a variation of a heart image and the text 'einander-helfen.de'. The creator of the picture must be mentioned on the 'About' page.

Is this outdated?

**Comment by MaiThiD** [comment]
> According to the wiki author must be mentioned on the about page (wiki > requirements):
> 
> > The logo contains a variation of a heart image and the text 'einander-helfen.de'. The creator of the picture must be mentioned on the 'About' page.
> 
> Is this outdated?

yes

**Comment by BaderChouaib** [comment]
@BernhardHumm suggested to put crediting into privacy page ("data protection")
https://github.com/hochschule-darmstadt/einander-helfen/issues/46#issuecomment-648709009

**Comment by BernhardHumm** [comment]
Mai Duong suggested that imprint is the better location for this. OK

 

 

 

------------------------------------

 

Von: BaderChouaib [mailto:notifications@github.com] 
Gesendet: Mittwoch, 24. Juni 2020 12:03
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] Copyright holder of the heart-hand-shake icon should be mentioned in imprint (#80)

 

@BernhardHumm <https://github.com/BernhardHumm>  suggested to put crediting into privacy page ("data protection")
#46 (comment) <https://github.com/hochschule-darmstadt/einander-helfen/issues/46#issuecomment-648709009>

**Comment by jschurse** [comment]
Fixed by #100
