### ISSUE TITLE
Deselect a selected post

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#87]
**Reason (Why?)**
The user shall be able to deselect the currently selected post.

**Solution (What?)**
The details view on the result page should contain a button (back arrow or "x") which deselects the current post and switches to the map view.

Please find an attractive solution how the deselecting and toggle buttons are placed in the detail view. The position of the toggle button should be exactly the same on the detail and map view.

**Not doing**
The function of the toggle button.

**Relation to other Issues**
#40: In this issue the toggle button was implemented and contains possible solutions for the implementation of this issue.

**Acceptance criteria**
The user can deselect a post.

**Comment by BernhardHumm** [comment]
Deselecting should also work by clicking on the selected list entry

 

 

 

------------------------------------

 

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Juni 2020 13:38
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Deselect a selected post (#87)

 

Reason (Why?)
The user shall be able to deselect the currently selected post.

Solution (What?)
The details view on the result page should contain a button (back arrow or "x") which deselects the current post and switches to the map view.

Please find an attractive solution how the deselecting and toggle buttons are placed in the detail view. The position of the toggle button should be exactly the same on the detail and map view.

Not doing
The function of the toggle button.

Relation to other Issues
#40 <https://github.com/hochschule-darmstadt/einander-helfen/issues/40> : In this issue the toggle button was implemented and contains possible solutions for the implementation of this issue.

Acceptance criteria
The user can deselect a post.

**Comment by tobias-hda** [comment]
I added an 'x'-Button and moved the detail and map button to the right side. 

![image](https://user-images.githubusercontent.com/64197565/86035642-f76ad800-ba3c-11ea-8514-db83edad7ac4.png)

I have placed the detail button next to the zoom buttons on the map. The position of the map and detail buttons are not exactly the same, because I think it would destroy the layout as they are placed now. @FiedlerJan @MaiThiD What do you think?

![image](https://user-images.githubusercontent.com/64197565/86036164-c212ba00-ba3d-11ea-9ec6-b6dca578a142.png)

**Comment by jschurse** [comment]
Hey,
looking good so far :)
I think it would be helpful to align the buttons at the top of the row. Otherwise when the title is longer they look a bit deplaced.
![image](https://user-images.githubusercontent.com/12964877/86062135-5265f480-ba68-11ea-8284-9e1b0c2eeba8.png)

**Comment by jschurse** [comment]
fixed by #119
