### ISSUE TITLE
Pagination does not switch to the selected post

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#89]
**Describe the bug**
When the user clicks on a pin in the map, the detail view is displayed correctly. However, the selected page is not changed.

**To Reproduce**
1. Go to 'https://cai-einander-helfen-staging.fbi.h-da.de/posts/?q=&location=&radius=&page=1'
2. Click on the pin 'BSBH - Begleitung Sehbehinderter'
![grafik](https://user-images.githubusercontent.com/64203299/85730071-a46de980-b6f9-11ea-9542-3144bbf478f9.png)
3. Scroll through the currently selected page
4. The page (1) does not contain the post
5. Go to page 4
6. The selected post is highlighted

**Expected behavior**
If the user clicks on a pin of the map the corresponding post is selected and the page is changed.

**Screenshots**
None

**Desktop (please complete the following information):**
Does not matter

**Smartphone (please complete the following information):**
Not used

**Additional context**
None

**Comment by jschurse** [comment]
I think this is somewhat related to #88 and will therefore be fixed by #91
