### ISSUE TITLE
Change everything from einander-helfen.de to einander-helfen.org

### ISSUE THREAD

**Issue by MaiThiD** [hochschule-darmstadt/einander-helfen#90]
**Reason (Why?)**
The site is www.einander-helfen.org and not www.einander-helfen.de

**Solution (What?)**
Change imprint and logo from einander-helfen.de to einander-helfen.org

**Not doing**
/
**Relation to other Issues**
/

**Acceptance criteria**
Imprint and logo are changed to einander-helfen.org

**Comment by jschurse** [comment]
We currently have this string capitalized and non capitalized:

non-capitalized
https://github.com/hochschule-darmstadt/einander-helfen/blob/staging/app/public/index.html#L8
https://github.com/hochschule-darmstadt/einander-helfen/blob/staging/app/src/components/layout/Toolbar.vue#L11

capitalized:
https://github.com/hochschule-darmstadt/einander-helfen/blob/staging/app/src/views/About.vue#L8
https://github.com/hochschule-darmstadt/einander-helfen/blob/staging/app/src/views/About.vue#L10

Should we unify this and if yes, shall all usages be capitalized or non-capitalized?

**Comment by MaiThiD** [comment]
> Should we unify this and if yes, shall all usages be capitalized or non-capitalized?

Everything should be non-capitalized.
