### ISSUE TITLE
Updated the cards on the home page

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#93]
**Reason (Why?)**
The labels of the cards on the home page shall match the given categories of "Ehrenamtssuche Hessen".

**Solution (What?)**
The labels of the cards should be:
* Denker/in
* Macher/in
* Kommunikative
* Soziale

The query behind the cards should correspond with the labels.

If the current images do not fit to the label, please exchange the images and list the author in the imprint.

**Not doing**
None

**Relation to other Issues**
None

**Acceptance criteria**
The labels of the cards match the given categories of "Ehrenamtssuche Hessen" and the search query contains the correct category.

**Comment by BernhardHumm** [comment]
I suggest the following selection (4 out of 5) and order:

Soziale

Kreative

Kommunikative

Macher/in

 

 

------------------------------------

 

Von: JanF [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Juni 2020 16:11
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hochschule-darmstadt/einander-helfen] Updated the cards on the home page (#93)

 

Reason (Why?)
The labels of the cards on the home page shall match the given categories of "Ehrenamtssuche Hessen".

Solution (What?)
The labels of the cards should be:

*	Denker/in
*	Macher/in
*	Kommunikative
*	Soziale

The query behind the cards should correspond with the labels.

If the current images do not fit to the label, please exchange the images and list the author in the imprint.

Not doing
None

Relation to other Issues
None

Acceptance criteria
The labels of the cards match the given categories of "Ehrenamtssuche Hessen" and the search query contains the correct category.
