### ISSUE TITLE
Default map on mobil

### ISSUE THREAD

**Issue by FiedlerJan** [hochschule-darmstadt/einander-helfen#96]
**Reason (Why?)**
In the mobile view, the map shall not block the view of the posts.

**Solution (What?)**
In the mobile view the map should be hidden by default. It should be possible to unfold and hide the map with a toggle button.

**Not doing**
None

**Relation to other Issues**
#76  

**Acceptance criteria**
In the mobile view, the user first sees the posts and can view the map.

**Comment by jschurse** [comment]
Is this still necessary when the map no longer traps the user on touch based devices?

**Comment by jschurse** [comment]
Proposal:
![image](https://user-images.githubusercontent.com/12964877/85956924-422b1800-b989-11ea-9109-652ac74695c8.png)

When the user focus the search field it gets expanded:
![image](https://user-images.githubusercontent.com/12964877/85956963-9209df00-b989-11ea-87ec-ea879564b320.png)

**Comment by jschurse** [comment]
To estimate if this is feasable I started implementing it here:
https://github.com/hochschule-darmstadt/einander-helfen/pull/117
I don't think I will have enough time left this semester for this feature, so feel free to contribute if you are interested.
